// Textos de la app en castellano rioplatense. Es el idioma de referencia: si
// a otro diccionario le falta una clave, se muestra lo que dice acá.
// Regla: texto nuevo = clave nueva acá Y en pt-BR.js (la prueba lo exige).
export default {
  comun: {
    cancelar: "Cancelar",
    volver: "Volver",
    guardar: "Guardar",
    guardando: "Guardando…",
    cerrar: "Cerrar",
    listo: "Listo",
    si: "Sí",
    no: "No",
    hoy: "Hoy",
    actualizar: "Actualizar",
    actualizando: "Actualizando…",
    reintentar: "Reintentar",
    cargando: "Cargando…",
    salir: "Salir",
    saliendo: "Saliendo…",
    sinConexion: "No hay conexión. Fijate la señal y probá de nuevo.",
    idioma: "Idioma",
    todos: "Todos",
    sinDato: "Sin dato",
    elegir: "Elegí…",
    borrar: "Borrar",
    filtros: "Filtros",
    quitarFiltros: "Quitar filtros",
    cambiar: "Cambiar",
  },
  nav: {
    partido: "Partido",
    formacion: "Formación",
    registros: "Registros",
    ajustes: "Ajustes",
    inicio: "Inicio",
    tareas: "Tareas",
    lesionados: "Lesionados",
    historial: "Historial",
    plantel: "Plantel",
  },
  acceso: {
    marca: "Registro Partido",
    volverPortal: "Volver al portal",
    cargandoTitulo: "Un momento…",
    cargandoTexto: "Estamos comprobando tu cuenta.",
    cargandoTarda: "Está tardando más de lo normal. Si no tenés señal, puede demorar hasta medio minuto.",
    recuperarTitulo: "Elegí una contraseña nueva",
    recuperarTexto: "De ahora en más vas a entrar con esta contraseña.",
    nuevaContrasena: "Nueva contraseña",
    repetirContrasena: "Repetir contraseña",
    guardarContrasena: "Guardar contraseña",
    pendienteTitulo: "Tu cuenta está pendiente de autorización",
    pendienteTexto: "La cuenta {{correo}} ya está creada. Cuando el administrador la autorice vas a poder entrar; si ya te avisó, tocá Volver a comprobar.",
    bloqueadoTitulo: "Tu cuenta no tiene acceso",
    bloqueadoTexto: "El administrador le quitó el acceso a esta cuenta. Si creés que es un error, hablá con él.",
    sinModulosTitulo: "Tu cuenta no tiene módulos habilitados",
    sinModulosTexto: "El administrador todavía no te habilitó ningún módulo. Cuando lo haga, tocá Volver a comprobar.",
    comprobar: "Volver a comprobar",
    comprobando: "Comprobando…",
    noPudimosTitulo: "No pudimos comprobar tu cuenta",
    noPudimosTexto: "Probá de nuevo en un momento.",
    entrarTitulo: "Entrá con tu cuenta",
    entrarTexto: "Usá el correo y la contraseña con los que te registraste.",
    correo: "Correo",
    contrasena: "Contraseña",
    correoEjemplo: "nombre@club.com",
    entrar: "Entrar",
    entrando: "Entrando…",
    olvide: "Olvidé mi contraseña",
    enviando: "Enviando…",
    crear: "Crear una cuenta",
    creando: "Creando…",
    notaAutorizacion: "Las cuentas nuevas necesitan la autorización del administrador antes de poder entrar.",
    error: {
      credenciales: "El correo o la contraseña no son correctos.",
      noConfirmado: "Todavía no confirmaste tu correo. Buscá el mensaje en tu casilla (también en spam).",
      yaRegistrado: "Ese correo ya tiene una cuenta. Entrá con tu contraseña o pedí una nueva.",
      demasiados: "Hubo demasiados intentos seguidos. Esperá unos minutos y probá de nuevo.",
      mismaContrasena: "La contraseña nueva tiene que ser distinta de la anterior.",
      debil: "La contraseña es muy fácil de adivinar. Usá al menos 8 caracteres, mezclando letras y números.",
      reautenticar: "Por seguridad, pedí un enlace nuevo desde Olvidé mi contraseña y probá otra vez.",
      enlaceVencido: "El enlace del correo venció o ya se usó. Pedí uno nuevo.",
      enlaceInvalido: "El enlace del correo no es válido. Pedí uno nuevo.",
      enlaceRecuperacion: "El enlace de recuperación no es válido o ya venció. Pedí uno nuevo desde Olvidé mi contraseña.",
      enlaceNoValido: "El enlace de recuperación no es válido. Pedí uno nuevo.",
      minimo8: "La contraseña nueva tiene que tener al menos 8 caracteres.",
      noCoinciden: "Las contraseñas no coinciden.",
      sesionNoAbierta: "No se pudo abrir la sesión después de cambiar la contraseña.",
      sinConexionCuenta: "No hay conexión y no pudimos comprobar tu cuenta. Probá de nuevo cuando tengas señal.",
      noComprobar: "No se pudo comprobar tu cuenta. Probá de nuevo.",
      noEntrar: "No se pudo entrar. Probá de nuevo.",
      completar: "Completá el correo y la contraseña.",
      noCrear: "No se pudo crear la cuenta.",
      escribiCorreo: "Primero escribí tu correo, así te mandamos el enlace.",
      noEnviarCorreo: "No se pudo enviar el correo de recuperación.",
      noCambiarContrasena: "No se pudo cambiar la contraseña.",
    },
    cuentaCreada: "Cuenta creada. Te mandamos un correo para confirmarla: abrí el enlace y volvé a entrar. Después el administrador tiene que autorizarla.",
    enlaceEnviado: "Si ese correo tiene una cuenta, te va a llegar un enlace para elegir una contraseña nueva. Revisá también la carpeta de spam.",
  },
  portal: {
    pregunta: "¿Qué vas a hacer hoy?",
    elegi: "Elegí por dónde arrancar.",
    unSolo: "Por ahora tenés habilitado este módulo.",
    cuentas: "Cuentas",
    modulos: "Módulos",
    salir: "Salir",
    entrar: "Entrar",
    entrarA: "Entrar a {{modulo}}",
    entrando: "Entrando…",
    enPrueba: "En prueba",
    nuevo: "Nuevo",
    partidoTitulo: "Partido",
    partidoTexto: "Registrá el partido en vivo: formación, tiempos y cambios.",
    flujoTitulo: "Flujo diario",
    flujoTexto: "Todo lo del día después de entrenar: cortes, datos, planilla y PSE.",
    lesionesTitulo: "Lesiones",
    lesionesTexto: "Quién está lesionado, desde cuándo y cuándo vuelve. Carga en cuatro toques.",
  },
  club: {
    titulo: "¿Con qué club trabajás?",
    texto: "Elegí el club. Después lo podés cambiar desde el portal.",
    cargando: "Buscando los clubes…",
    vacio: "Todavía no hay clubes cargados. Creá el primero.",
    error: "No se pudieron leer los clubes.",
    crear: "Crear un club",
    nombre: "Nombre del club",
    crearBoton: "Crear y elegir",
    creando: "Creando…",
    cambiar: "Cambiar de club",
    elegido: "Club",
  },
  openfield: {
    abriendoTitulo: "Un momento…",
    abriendoTexto: "Estamos conectando con OpenField.",
    sinAccesoTitulo: "Sin acceso a Flujo diario",
    errorTitulo: "No pudimos conectar con OpenField",
    errorTexto: "No se pudo abrir la sesión de OpenField. Probá de nuevo.",
    iniciaSesion: "Iniciá sesión para acceder a OpenField.",
  },
  cuentas: {
    kicker: "Administración",
    titulo: "Cuentas",
    texto: "Acá decidís quién puede entrar a la app y qué módulos usa cada uno. Los cambios se aplican en el momento.",
    porAutorizar: "Por autorizar",
    conAcceso: "Con acceso",
    sinAcceso: "Sin acceso",
    vacioPendientes: "No hay cuentas esperando autorización.",
    vacioConAcceso: "Todavía no hay cuentas con acceso.",
    vacioSinAcceso: "No hay cuentas sin acceso.",
    tuCuenta: "Tu cuenta",
    administrador: "Administrador",
    correoSinConfirmar: "Correo sin confirmar",
    creadaEl: "Creada el {{fecha}}",
    ultimoCambio: "· Último cambio el {{fecha}}",
    autorizar: "Autorizar",
    rechazar: "Rechazar",
    quitarAcceso: "Quitar acceso",
    quePuedeUsar: "Qué puede usar {{correo}}",
    modulos: {
      partido: "Partido",
      flujo: "Flujo diario",
      lesiones: "Lesiones",
      admin: "Administrador",
    },
    errorLeer: "No se pudieron leer las cuentas.",
    errorCambiar: "No se pudo cambiar la cuenta.",
    marcaModulo: "Marcá al menos un módulo antes de autorizar.",
    rechazarTitulo: "¿Rechazar esta cuenta?",
    quitarTitulo: "¿Quitar el acceso?",
    rechazarTexto: "{{correo}} no va a poder entrar a la app. Si cambiás de idea, la podés autorizar desde Sin acceso.",
    quitarTexto: "{{correo}} deja de tener acceso a la app en el momento. Podés volver a autorizarla cuando quieras.",
    siRechazar: "Sí, rechazar",
    siQuitar: "Sí, quitar",
    laCuenta: "La cuenta",
    sinCorreo: "(sin correo)",
  },
  lesiones: {
    titulo: "Lesiones",
    hoy: "Lesionados hoy",
    activas_one: "{{n}} lesión activa",
    activas_other: "{{n}} lesiones activas",
    sinActivas: "No hay lesiones activas. Todo el plantel está disponible.",
    nueva: "Nueva lesión",
    darAlta: "Alta médica",
    borrar: "Borrar lesión",
    borrarTitulo: "¿Borrar esta lesión?",
    borrarTexto: "Se borra la lesión de {{jugador}}. Queda anotado en el historial de cambios.",
    siBorrar: "Sí, borrar",
    borrada: "Lesión borrada",
    editar: "Editar",
    dias_one: "{{n}} día",
    dias_other: "{{n}} días",
    desde: "desde el {{fecha}}",
    altaEl: "alta el {{fecha}}",
    gravedad: {
      minima: "Mínima",
      leve: "Leve",
      moderada: "Moderada",
      grave: "Grave",
      activa: "Activa",
    },
    altaTitulo: "¿Dar el alta médica?",
    altaTexto: "{{jugador}} vuelve a estar disponible desde la fecha que elijas.",
    altaFecha: "Fecha del alta médica",
    siAlta: "Sí, dar el alta",
    formNueva: "Nueva lesión",
    formEditar: "Editar lesión",
    jugador: "Jugador",
    buscarJugador: "Buscar por nombre",
    sinJugadores: "No hay jugadores cargados. Se agregan en Partido › Ajustes › Jugadores.",
    fechaLesion: "Fecha de la lesión",
    fechaAlta: "Fecha del alta médica (vuelve a entrenar)",
    yaTieneAlta: "Ya tiene el alta médica",
    sinAlta: "Sin alta médica: la lesión sigue activa.",
    contexto: "Dónde pasó",
    modoInicio: "Cómo empezó",
    mecanismo: "Mecanismo",
    region: "Región",
    lado: "Lado",
    tejido: "Tejido",
    diagnostico: "Diagnóstico",
    diagnosticoAyuda: "Opcional. Corto, sin datos personales de más.",
    observaciones: "Observaciones",
    guardado: "Lesión guardada",
    altaGuardada: "Alta guardada",
    avisoRecidiva: "Posible recidiva: ya tuvo una lesión en {{region}} ({{lado}}) el {{fecha}}.",
    error: {
      jugador: "Elegí un jugador.",
      fecha: "Cargá la fecha de la lesión.",
      fechaFutura: "La fecha no puede ser futura.",
      altaAntes: "El alta no puede ser anterior a la lesión.",
      altaFutura: "La fecha del alta no puede ser futura.",
      region: "Elegí la región.",
      lado: "Elegí el lado.",
      solapada: "Ya hay una lesión activa en {{region}} ({{lado}}) para este jugador.",
      noGuardar: "No se pudo guardar la lesión.",
      noBorrar: "No se pudo borrar la lesión.",
      noLeer: "No se pudieron leer las lesiones.",
      faltaMigracion: "La base todavía no tiene la tabla de lesiones: falta ejecutar la migración 20261001_lesiones.sql en Supabase.",
      sinPermiso: "Tu cuenta no tiene permiso para cargar lesiones.",
    },
    opciones: {
      contexto: { entrenamiento: "Entrenamiento", partido: "Partido", otro: "Otro" },
      modo: { subito: "De golpe", gradual: "Gradual" },
      mecanismo: { contacto_directo: "Contacto directo", contacto_indirecto: "Contacto indirecto", sin_contacto: "Sin contacto" },
      lado: { derecho: "Derecho", izquierdo: "Izquierdo", bilateral: "Bilateral", no_aplica: "No aplica" },
      tejido: { muscular: "Muscular", tendon: "Tendón", ligamento: "Ligamento", hueso: "Hueso", articular: "Articular", contusion: "Contusión", otro: "Otro" },
      region: {
        cabeza_cuello: "Cabeza y cuello",
        hombro: "Hombro",
        brazo_codo: "Brazo y codo",
        antebrazo_mano: "Antebrazo y mano",
        torax_espalda: "Tórax y espalda",
        lumbar: "Zona lumbar",
        cadera_ingle: "Cadera e ingle",
        muslo_anterior: "Muslo anterior (cuádriceps)",
        muslo_posterior: "Muslo posterior (isquios)",
        aductores: "Aductores",
        rodilla: "Rodilla",
        pierna: "Pierna (gemelo y sóleo)",
        tobillo: "Tobillo",
        pie: "Pie",
      },
    },
    plantel: {
      titulo: "Plantel",
      texto: "Quién está disponible hoy.",
      disponibles: "{{n}} de {{total}} disponibles",
      disponible: "Disponible",
      lesionado: "Lesionado",
      sinPlantel: "No hay jugadores cargados en este equipo.",
    },
    historial: {
      titulo: "Historial",
      texto: "Todas las lesiones cargadas, de la más reciente a la más vieja.",
      vacio: "Todavía no hay lesiones cargadas.",
      sinResultados: "Ninguna lesión coincide con los filtros.",
      todos: "Todos los jugadores",
      todas: "Todas",
      estado: "Estado",
      activas: "Activas",
      conAlta: "Con alta médica",
      cantidad_one: "{{n}} lesión",
      cantidad_other: "{{n}} lesiones",
      cambios: "Historial de cambios",
      sinCambios: "Sin cambios registrados.",
      cambio: "{{fecha}} · {{quien}}",
      creada: "Carga",
      editada: "Edición",
    },
    ajustes: {
      titulo: "Ajustes",
      texto: "Lo que la app usa en Lesiones.",
      listas: "Listas",
      listasTexto: "Las opciones de cada desplegable.",
      listasAyuda: "Cuando definamos las cabeceras del Excel, desde acá se van a poder agregar o sacar opciones sin tocar el código.",
      opciones_one: "{{n}} opción",
      opciones_other: "{{n}} opciones",
    },
    estado: {
      cargando: "Leyendo las lesiones…",
      sinConexion: "Sin conexión. Lesiones necesita señal para leer y guardar.",
    },
  },
};
