// Textos de la app en castellano rioplatense. Es el idioma de referencia: si
// a otro diccionario le falta una clave, se muestra lo que dice acá.
// Regla: texto nuevo = clave nueva acá Y en pt-BR.js (la prueba lo exige).
export default {
  comun: {
    cancelar: "Cancelar",
    volver: "Volver",
    guardar: "Guardar",
    guardando: "Guardando…",
    cerrar: "Cerrar",
    listo: "Listo",
    si: "Sí",
    no: "No",
    hoy: "Hoy",
    actualizar: "Actualizar",
    actualizando: "Actualizando…",
    reintentar: "Reintentar",
    cargando: "Cargando…",
    salir: "Salir",
    saliendo: "Saliendo…",
    sinConexion: "No hay conexión. Fijate la señal y probá de nuevo.",
    idioma: "Idioma",
    todos: "Todos",
    sinDato: "Sin dato",
    buscar: "Escribir para buscar...",
    sinCoincidencias: "Sin coincidencias.",
    elegir: "Elegí…",
    borrar: "Borrar",
    filtros: "Filtros",
    quitarFiltros: "Quitar filtros",
    cambiar: "Cambiar",
  },
  nav: {
    partido: "Partido",
    formacion: "Formación",
    registros: "Registros",
    ajustes: "Ajustes",
    inicio: "Inicio",
    tareas: "Tareas",
    lesionados: "Nuevos casos",
    historial: "Historial individual",
    base: "Base",
    jugadores: "Jugadores",
    reportes: "Reportes",
    posiciones: "Posiciones",
    catapult: "Catapult",
    referencias: "Valores de referencia",
  },
  acceso: {
    marca: "Registro Partido",
    volverPortal: "Volver al portal",
    cargandoTitulo: "Un momento…",
    cargandoTexto: "Estamos comprobando tu cuenta.",
    cargandoTarda: "Está tardando más de lo normal. Si no tenés señal, puede demorar hasta medio minuto.",
    cargandoTardaConCopia: "Está tardando más de lo normal. Si la señal no te deja, podés entrar con la cuenta guardada en este celular.",
    entrarSinConexion: "Entrar sin conexión",
    recuperarTitulo: "Elegí una contraseña nueva",
    recuperarTexto: "De ahora en más vas a entrar con esta contraseña.",
    nuevaContrasena: "Nueva contraseña",
    repetirContrasena: "Repetir contraseña",
    guardarContrasena: "Guardar contraseña",
    pendienteTitulo: "Tu cuenta está pendiente de autorización",
    pendienteTexto: "La cuenta {{correo}} ya está creada. Si te invitaron a un club, confirmá este correo (te llegó un mail) y tocá Volver a comprobar. Si no, pedile al administrador de tu club que te invite con este correo.",
    bloqueadoTitulo: "Tu cuenta no tiene acceso",
    bloqueadoTexto: "El administrador le quitó el acceso a esta cuenta. Si creés que es un error, hablá con él.",
    sinModulosTitulo: "Tu cuenta no tiene módulos habilitados",
    sinModulosTexto: "El administrador todavía no te habilitó ningún módulo. Cuando lo haga, tocá Volver a comprobar.",
    comprobar: "Volver a comprobar",
    comprobando: "Comprobando…",
    noPudimosTitulo: "No pudimos comprobar tu cuenta",
    noPudimosTexto: "Probá de nuevo en un momento.",
    entrarTitulo: "Entrá con tu cuenta",
    entrarTexto: "Usá el correo y la contraseña con los que te registraste.",
    correo: "Correo",
    contrasena: "Contraseña",
    correoEjemplo: "nombre@club.com",
    entrar: "Entrar",
    entrando: "Entrando…",
    olvide: "Olvidé mi contraseña",
    enviando: "Enviando…",
    crear: "Crear una cuenta",
    creando: "Creando…",
    notaAutorizacion: "Las cuentas nuevas necesitan la autorización del administrador antes de poder entrar.",
    error: {
      credenciales: "El correo o la contraseña no son correctos.",
      noConfirmado: "Todavía no confirmaste tu correo. Buscá el mensaje en tu casilla (también en spam).",
      yaRegistrado: "Ese correo ya tiene una cuenta. Entrá con tu contraseña o pedí una nueva.",
      demasiados: "Hubo demasiados intentos seguidos. Esperá unos minutos y probá de nuevo.",
      mismaContrasena: "La contraseña nueva tiene que ser distinta de la anterior.",
      debil: "La contraseña es muy fácil de adivinar. Usá al menos 8 caracteres, mezclando letras y números.",
      reautenticar: "Por seguridad, pedí un enlace nuevo desde Olvidé mi contraseña y probá otra vez.",
      enlaceVencido: "El enlace del correo venció o ya se usó. Pedí uno nuevo.",
      enlaceInvalido: "El enlace del correo no es válido. Pedí uno nuevo.",
      enlaceRecuperacion: "El enlace de recuperación no es válido o ya venció. Pedí uno nuevo desde Olvidé mi contraseña.",
      enlaceNoValido: "El enlace de recuperación no es válido. Pedí uno nuevo.",
      minimo8: "La contraseña nueva tiene que tener al menos 8 caracteres.",
      noCoinciden: "Las contraseñas no coinciden.",
      sesionNoAbierta: "No se pudo abrir la sesión después de cambiar la contraseña.",
      sinConexionCuenta: "No hay conexión y no pudimos comprobar tu cuenta. Probá de nuevo cuando tengas señal.",
      noComprobar: "No se pudo comprobar tu cuenta. Probá de nuevo.",
      noEntrar: "No se pudo entrar. Probá de nuevo.",
      completar: "Completá el correo y la contraseña.",
      noCrear: "No se pudo crear la cuenta.",
      escribiCorreo: "Primero escribí tu correo, así te mandamos el enlace.",
      noEnviarCorreo: "No se pudo enviar el correo de recuperación.",
      noCambiarContrasena: "No se pudo cambiar la contraseña.",
    },
    cuentaCreada: "Cuenta creada. Te mandamos un correo para confirmarla: abrí el enlace y volvé a entrar. Después el administrador tiene que autorizarla.",
    enlaceEnviado: "Si ese correo tiene una cuenta, te va a llegar un enlace para elegir una contraseña nueva. Revisá también la carpeta de spam.",
  },
  portal: {
    pregunta: "¿Qué vas a hacer hoy?",
    elegi: "Elegí por dónde arrancar.",
    unSolo: "Por ahora tenés habilitado este módulo.",
    cuentas: "Cuentas",
    modulos: "Módulos",
    salir: "Salir",
    entrar: "Entrar",
    entrarA: "Entrar a {{modulo}}",
    entrando: "Entrando…",
    enPrueba: "En prueba",
    nuevo: "Nuevo",
    partidoTitulo: "Partido",
    partidoTexto: "Registrá el partido en vivo: formación, tiempos y cambios.",
    flujoTitulo: "Flujo diario",
    flujoTexto: "Todo lo del día después de entrenar: cortes, datos, planilla y PSE.",
    basesTitulo: "Bases de Datos",
    basesTexto: "Cada base del club en un solo lugar, para cargar, mirar y sacar reportes.",
    datosTitulo: "Datos básicos",
    datosTexto: "Los jugadores y sus datos, en una tabla que se copia y se pega como en Excel.",
  },
  // Bases de Datos: una tarjeta por base, como en la pantalla principal.
  bases: {
    elegi: "Elegí qué base abrir.",
    ninguna: "Tu cuenta no tiene ninguna base habilitada en este club.",
    lesionesTitulo: "Lesiones",
    lesionesTexto: "Quién está lesionado, desde cuándo y cuándo vuelve, con la base y los reportes.",
    evaluacionesTitulo: "Evaluaciones",
    evaluacionesTexto: "Los tests físicos de cada jugador, con su informe, los valores de referencia y los mismos colores del Excel.",
  },
  evaluaciones: {
    titulo: "Evaluaciones",
    texto: "Como en el Excel: el informe de arriba y los colores se recalculan con las filas que deja ver el filtro.",
    agregar: "Agregar evaluación",
    agregarTitulo: "¿De quién es la evaluación?",
    agregada: "Evaluación agregada: completala en la tabla.",
    borrarTitulo: "¿Borrar esta evaluación?",
    borrarTexto: "La de {{jugador}} del {{fecha}}. No se puede deshacer.",
    sinFecha: "sin fecha",
    siBorrar: "Sí, borrar",
    borrada: "Evaluación borrada.",
    comparar: "Comparar con",
    sinReferencias: "Todavía no están los valores de referencia de este test: las clases quedan vacías hasta que se carguen.",
    totalEvaluaciones: "Cuántas evaluaciones se ven",
    estado: {
      cargando: "Leyendo las evaluaciones…",
      sinConexion: "Sin conexión. Evaluaciones necesita señal para leer y guardar.",
    },
    referencias: {
      titulo: "Valores de referencia",
      texto: "Los del Excel, por categoría: con ellos se calcula cada clase y la comparación del informe.",
      resumen: "RESUMEN CATEGORIAS (Promedios)",
      categoria: "Categoría",
      pro: "Pro",
      sinDatos: "Todavía no están los valores de referencia de este test. Se cargan una sola vez, con los valores exactos del Excel.",
    },
    importar: {
      boton: "Pegar desde Excel",
      titulo: "Pegar evaluaciones desde Excel",
      texto: "En el Excel, en la hoja del test, sacá los filtros y copiá la tabla desde la fila de títulos (la que dice nº Eva, Fecha, Jugador…) hasta la última evaluación, y pegala acá. Antes de cargar se ve qué pasa con cada fila. Lo que el Excel calcula no se pega: lo calcula la app.",
      pegarAca: "Pegá acá lo que copiaste del Excel",
      borrar: "Borrar lo pegado",
      sinCabeceras: "No encontré la fila de títulos. Copiá la tabla junto con la fila que dice Jugador.",
      sinFilas: "Debajo de los títulos no hay evaluaciones.",
      anio: "Las fechas vienen sin año: ¿de qué año son?",
      anioAyuda: "Si son de años distintos, en el Excel poné la columna Fecha con formato dd/mm/aaaa y volvé a copiar.",
      filas_one: "{{n}} fila en lo pegado",
      filas_other: "{{n}} filas en lo pegado",
      nuevas_one: "{{n}} para cargar",
      nuevas_other: "{{n}} para cargar",
      yaEstan_one: "{{n}} ya está en la app",
      yaEstan_other: "{{n}} ya están en la app",
      conProblemas_one: "{{n}} con problemas",
      conProblemas_other: "{{n}} con problemas",
      porElegir_one: "{{n}} para elegir",
      porElegir_other: "{{n}} para elegir",
      noVan_one: "{{n}} no se carga",
      noVan_other: "{{n}} no se cargan",
      fueraDeDatos_one: "{{n}} nombre no está en Datos básicos: tocalo para elegir qué hacer, o guardalo igual.",
      fueraDeDatos_other: "{{n}} nombres no están en Datos básicos: tocá cada uno para elegir qué hacer, o guardalos igual.",
      guardarTodasIgual_one: "Guardar igual la que no está en Datos básicos",
      guardarTodasIgual_other: "Guardar igual las {{n}} que no están en Datos básicos",
      quienEs: "¿Qué hacemos con {{nombre}}?",
      comoPersona: "Guardar con este nombre (no se agrega a Datos básicos)",
      noCargar: "No cargar",
      es: "Es {{jugador}}",
      seGuardaComoPersona: "No está en Datos básicos: la evaluación se guarda con este nombre y el nombre no se agrega a Datos básicos.",
      seGuardaComo: "No está en Datos básicos: la evaluación se guarda como {{nombre}}, escrito como en otra evaluación de la misma persona, y el nombre no se agrega a Datos básicos.",
      estado: {
        nueva: "Se carga",
        yaEsta: "Ya está en la app",
        sinJugador: "No está en Datos básicos",
        dudoso: "¿Quién es?",
        comoPersona: "Se guarda con este nombre",
        noVa: "No se carga",
        conProblemas: "No se carga",
      },
      sinJugador: "Este nombre no está en Datos básicos. Elegí si se guarda con este nombre (no se agrega a Datos básicos), si es un jugador de la lista o si no se carga.",
      jugadorDudoso: "En Datos básicos hay más de un jugador con un nombre así: elegí cuál es, o guardalo con este nombre.",
      fechaMal: "La fecha no se entiende: escribila como 12/06/2026.",
      fechaFutura: "La fecha es posterior a hoy.",
      repetida: "Esta evaluación está dos veces en lo pegado.",
      nombreLargo: "El nombre es demasiado largo para guardarlo (hasta 120 letras).",
      sinNombre: "Falta el nombre: no se sabe de quién es.",
      sinNombreFila: "Sin nombre",
      plantelSinLeer: "No se pudo leer Datos básicos, y sin eso no se sabe quién es cada uno. Volvé y probá de nuevo.",
      quedanSinElegir_one: "{{n}} nombre sigue sin elegir: esa evaluación no se carga hasta que elijas qué hacer.",
      quedanSinElegir_other: "{{n}} nombres siguen sin elegir: esas evaluaciones no se cargan hasta que elijas qué hacer.",
      aviso: "«{{valor}}» no se entendió en {{columna}}: queda vacío.",
      cargar_one: "Cargar {{n}} evaluación",
      cargar_other: "Cargar {{n}} evaluaciones",
      nadaQueCargar: "Nada para cargar",
      cargando: "Cargando {{n}} de {{total}}…",
      listo_one: "Listo: se cargó {{n}} evaluación.",
      listo_other: "Listo: se cargaron {{n}} evaluaciones.",
      fallaron_one: "{{n}} evaluación no se pudo cargar:",
      fallaron_other: "{{n}} evaluaciones no se pudieron cargar:",
      fallo: "{{fecha}} · {{nombre}}: {{error}}",
    },
    error: {
      noLeer: "No se pudieron leer las evaluaciones.",
      noGuardar: "No se pudo guardar la evaluación.",
      noBorrar: "No se pudo borrar la evaluación.",
      faltaMigracion: "La base todavía no tiene Evaluaciones: falta correr el SQL 20261012_evaluaciones.sql en Supabase.",
      jugadorDeOtroClub: "Ese jugador no es de este club.",
      fechaFutura: "La fecha de la evaluación no puede ser posterior a hoy.",
      sinJugador: "Una evaluación tiene que ser de alguien: elegí el jugador.",
      sinPermiso: "Tu cuenta no tiene Evaluaciones en este club.",
      sinConexion: "Sin conexión: no se pudo guardar.",
    },
  },
  tabla: {
    copiar: "Copiar",
    pegar: "Pegar",
    ficha: "Ver ficha",
    borrarFila: "Borrar fila",
    sinSeleccion: "Tocá una celda para empezar. Mantené apretada una cabecera para moverla o arrastrá su borde para cambiar el ancho.",
    filas_one: "{{n}} fila",
    filas_other: "{{n}} filas",
    filasDe_one: "{{n}} de {{total}} fila",
    filasDe_other: "{{n}} de {{total}} filas",
    ancho: "Arrastrá para cambiar el ancho (dos clics: vuelve al de siempre)",
    seleccion_one: "{{n}} celda elegida",
    seleccion_other: "{{n}} celdas elegidas",
    copiado_one: "{{n}} celda copiada",
    copiado_other: "{{n}} celdas copiadas",
    pegado_one: "{{n}} celda pegada",
    pegado_other: "{{n}} celdas pegadas",
    ignoradas_one: "{{n}} no se entendió o no se puede cambiar",
    ignoradas_other: "{{n}} no se entendieron o no se pueden cambiar",
    horasMalEscritas: "Las horas se escriben como en el Excel: 30:14:20, 30:14 o 30,5.",
    tiempoMalEscrito: "Los tiempos se escriben en minutos y segundos: 3:04 o 3,04 (o 45, solo segundos).",
    nadaQuePegar: "No hay nada para pegar. Copiá celdas de Excel o de esta tabla.",
    sinPermisoPegar: "El celular no deja leer lo copiado. Pegá con Ctrl+V dentro de una celda.",
    editar: "Tocá dos veces una celda para cambiarla.",
    vacio: "Todavía no hay filas.",
    guardando: "Guardando…",
    filtrar: "Filtrar u ordenar {{columna}}",
    filtroTitulo: "Filtrar: {{columna}}",
    buscarValor: "Buscar…",
    todos: "Todos",
    ninguno: "Ninguno",
    vacias: "(Vacías)",
    ordenarAsc: "De menor a mayor",
    ordenarDesc: "De mayor a menor",
    quitarFiltro: "Quitar filtro",
    aplicar: "Aplicar",
    quitarFiltros: "Quitar filtros",
    sinResultados: "Ninguna fila entra en los filtros.",
    nadaEnLista: "Ningún valor coincide.",
  },
  datos: {
    titulo: "Datos básicos",
    texto: "Los jugadores del club con lo que cada módulo necesita. Tocá una celda para elegirla, dos veces para cambiarla.",
    textoCorto: "Los jugadores del club con lo que cada módulo necesita.",
    agregar: "Agregar jugador",
    nombre: "Nombre y apellido",
    foto: "Foto (enlace)",
    horasPrevias: "Horas previas",
    actual: "Actual",
    yaNoEsta: "Ya no está",
    leyendaYaNoEsta: "En este color, los que ya no están en el plantel actual (Datos básicos › Actual).",
    actuales_one: "{{n}} en el plantel actual",
    actuales_other: "{{n}} en el plantel actual",
    agregado: "Jugador agregado",
    borrarTitulo: "¿Borrar al jugador?",
    borrarTexto: "Borrar es para un jugador cargado por error: {{jugador}} sale de la lista de todos los módulos. Si ya no está en el club, mejor desmarcá Actual (sus datos quedan). Con lesiones o evaluaciones cargadas no se puede borrar.",
    siBorrar: "Sí, borrar",
    borrado: "Jugador borrado",
    guardado: "Guardado",
    jugadores_one: "{{n}} jugador",
    jugadores_other: "{{n}} jugadores",
    importar: {
      boton: "Pegar desde Excel",
      titulo: "Pegar desde Excel",
      texto: "En el Excel, copiá la tabla de Datos Básicos junto con la fila de cabeceras (Nome e Sobrenome, Categoria, D. Nac., P. Dominante, Posicao, Links das fotos) y pegala acá. Antes de cargar se ve qué pasa con cada jugador.",
      pegarAca: "Pegá acá lo que copiaste del Excel",
      borrar: "Borrar lo pegado",
      sinCabeceras: "No encontré la fila de cabeceras. Copiá la tabla junto con la fila que dice Nome e Sobrenome.",
      sinFilas: "Debajo de las cabeceras no hay jugadores.",
      jugadores_one: "{{n}} jugador en lo pegado",
      jugadores_other: "{{n}} jugadores en lo pegado",
      nuevos_one: "{{n}} nuevo",
      nuevos_other: "{{n}} nuevos",
      conCambios: "{{n}} con cambios",
      iguales: "{{n}} sin cambios",
      quienEs: "¿Quién es {{nombre}} en la app?",
      nuevo: "Jugador nuevo",
      noCargar: "No cargar",
      es: "Es {{jugador}}",
      pareceSer: "¿Es {{jugador}}?",
      repetido: "Repetido en lo pegado",
      trae: "Trae: {{columnas}}",
      cambia: "Cambia: {{columnas}}",
      sinCambios: "Ya tiene estos datos.",
      cambiaria: "Si es él, cambia: {{columnas}}",
      confirmar: "Sí, es {{jugador}}",
      porConfirmar_one: "{{n}} para confirmar",
      porConfirmar_other: "{{n}} para confirmar",
      sinDatos: "Solo el nombre.",
      aviso: "«{{valor}}» no se entendió en {{columna}}: queda como está.",
      cargar_one: "Cargar {{n}} jugador",
      cargar_other: "Cargar {{n}} jugadores",
      nadaQueCargar: "Nada para cargar",
      cargando: "Cargando {{n}} de {{total}}…",
      listo: "Listo: {{nuevos}} y {{actualizados}}.",
      actualizados_one: "{{n}} actualizado",
      actualizados_other: "{{n}} actualizados",
      fallaron_one: "{{n}} jugador no se pudo cargar:",
      fallaron_other: "{{n}} jugadores no se pudieron cargar:",
      fallo: "{{nombre}}: {{error}}",
      sinDatosGuardados: "se agregó, pero sus datos no se guardaron ({{error}})",
    },
    error: {
      nombre: "Escribí el nombre.",
      repetido: "Ese jugador ya está en la lista. Si volvió al club, marcá Actual.",
      guardar: "No se pudo guardar.",
      leer: "No se pudieron leer los jugadores.",
      horas: "Las horas se escriben como en el Excel: 30:14:20, 30:14 o 30,5.",
      nacimientoFuturo: "La fecha de nacimiento no puede ser posterior a hoy.",
      borrar: "No se pudo borrar.",
      faltanHorasPrevias: "Para guardar las horas previas falta correr en Supabase el SQL de las horas previas.",
      borrarConDatos: "Tiene lesiones o evaluaciones cargadas y no se puede borrar: si ya no está en el club, desmarcá Actual.",
      faltaActual: "Para marcar quién está en el plantel actual falta correr en Supabase el SQL 20261011_jugadores_actual.sql.",
    },
    vacio: "Todavía no hay jugadores cargados.",
    posiciones: {
      titulo: "Dónde juega cada uno",
      texto: "Los puestos y los roles que usa Partido para armar la formación.",
      buscar: "Buscar jugador",
      nadie: "Ningún jugador con ese nombre.",
      agregarPuesto: "Agregar puesto",
      quitarPuesto: "Quitar este puesto",
    },
    puestos: {
      LAT: "Lateral",
      CAR: "Carrilero",
      DEF: "Defensor",
      VD: "Volante defensivo",
      VC: "Volante central",
      VM: "Volante mixto",
      VOL: "Volante",
      VO: "Volante ofensivo",
      EXT: "Extremo",
      MP: "Mediapunta",
      DEL: "Delantero",
    },
    roles: {
      Defensa: "Defensa",
      Mediocampo: "Mediocampo",
      Ataque: "Ataque",
    },
    catapult: {
      titulo: "Chalecos de Catapult",
      texto: "Cada jugador se empareja una vez con su chaleco para que los datos de Flujo diario lleguen a la persona correcta.",
      noLeer: "No se pudo leer la lista de jugadores.",
      faltaMigracion: "La lista de jugadores todavía no tiene el vínculo con Catapult: falta ejecutar la migración 20260920_jugadores_catapult.sql en Supabase.",
      yaVinculado: "Ese atleta de Catapult ya está vinculado a otro jugador.",
      noChalecos: "No se pudieron leer los chalecos.",
      conChaleco: "{{n}} con chaleco",
      chaleco: "Chaleco: {{chaleco}}",
      chalecoDe: "Chaleco de {{jugador}}",
      sinChaleco: "Sin chaleco",
      opcionSin: "— Sin chaleco —",
      repetido: "Repetido",
      yaNoExiste: "Ese chaleco ya no existe",
      guardado: "Guardado",
      exacto: "Coincide solo",
      probable: "Parecido, revisalo",
      aMano: "Elegido a mano",
      emparejar: "Emparejar con los chalecos",
      emparejarTexto: "Busca los chalecos de las últimas sesiones y propone quién es quién. Después guardás.",
      buscar: "Buscar chalecos",
      buscando: "Buscando…",
      resumen: "Chalecos encontrados: {{chalecos}} · coinciden solos: {{exactos}} · parecidos: {{probables}} · sin propuesta: {{sinPropuesta}} · ya no existen: {{ausentes}}",
      hayRepetidos: "Hay un chaleco elegido para más de un jugador. Corregilo antes de guardar.",
      sinCambios: "Sin cambios para guardar",
      guardar_one: "Guardar {{n}} cambio",
      guardar_other: "Guardar {{n}} cambios",
      guardados_one: "{{n}} cambio guardado.",
      guardados_other: "{{n}} cambios guardados.",
    },
  },
  club: {
    titulo: "¿Con qué club trabajás?",
    texto: "Elegí el club. Después lo podés cambiar desde el portal.",
    cargando: "Buscando los clubes…",
    vacio: "Todavía no estás en ningún club. Pedile al administrador de tu club que te invite con tu correo: {{correo}}.",
    vacioDueno: "Todavía no hay clubes. Creá el primero.",
    error: "No se pudieron leer los clubes.",
    crear: "Crear un club",
    nombre: "Nombre del club",
    crearBoton: "Crear y elegir",
    creando: "Creando…",
    cambiar: "Cambiar de club",
    elegido: "Club",
    hasta: "Hasta el {{fecha}} · solo lectura",
    sinMembresia: "No estás en este club",
    soloLecturaTitulo: "Dejaste este club el {{fecha}}.",
    soloLecturaTexto: "Ves lo cargado hasta ese día. No se puede agregar ni cambiar nada.",
    soloLecturaCambio: "Solo lectura: dejaste este club.",
  },
  // Textos nuevos del módulo Partido (App.js). El resto de esa pantalla
  // todavía está escrito en castellano directamente en el código.
  partido: {
    reanudarTitulo: "¿Reanudar el {{periodo}}?",
    reanudarTexto: "Se borra el final cargado ({{final}}) y el reloj vuelve a correr. Si después tocás Finalizar, queda la hora de ese momento.",
    reanudarSi: "Sí, reanudar",
    seguirEditando: "Seguir editando",
    salirSinGuardarTitulo: "¿Salir sin guardar los cambios?",
    salirSinGuardarTexto: "Lo que cambiaste en este registro todavía no se guardó. Si salís, se pierde.",
    salirSinGuardarSi: "Sí, salir",
    descartarFormacionTitulo: "¿Descartar la formación sin guardar?",
    descartarFormacionTexto: "Cambiaste la formación y todavía no la guardaste. Si la descartás, queda la que tiene el partido.",
    descartarFormacionSi: "Descartar",
    equipoSinPermisoRenombrar: "No tenés permiso para cambiar el nombre de este equipo. Lo cambia quien administra el club.",
    equipoSinPermisoCrear: "No tenés permiso para crear equipos. Los crea quien administra la plataforma.",
    equipoRepetido: "Ya hay un equipo con ese nombre.",
    equipoSinNombre: "Escribí el nombre del equipo.",
    equipoErrorRenombrar: "No se pudo cambiar el nombre. Fijate la señal y probá de nuevo.",
    equipoErrorCrear: "No se pudo crear el equipo. Fijate la señal y probá de nuevo.",
  },
  openfield: {
    abriendoTitulo: "Un momento…",
    abriendoTexto: "Estamos conectando con OpenField.",
    sinAccesoTitulo: "Sin acceso a Flujo diario",
    errorTitulo: "No pudimos conectar con OpenField",
    errorTexto: "No se pudo abrir la sesión de OpenField. Probá de nuevo.",
    iniciaSesion: "Iniciá sesión para acceder a OpenField.",
    servidorCaido: "OpenField no responde: podés seguir trabajando y probar de nuevo en un rato.",
    reintentando: "Probando…",
  },
  cuentas: {
    kicker: "Administración",
    titulo: "Cuentas",
    texto: "Quién entra a cada club, con qué rol y qué módulos. Los cambios valen en el momento.",
    pestanaClub: "Gente del club",
    pestanaPlataforma: "Cuentas de la app",
    club: "Club",
    clubTexto: "Quien se va sigue viendo lo cargado hasta su último día, sin poder cambiar nada. Si vuelve, se lo reincorpora con la misma cuenta.",
    plataformaTexto: "Las cuentas de toda la app. A qué club entra cada una se decide desde la gente de cada club.",
    sinClubes: "No administrás ningún club.",
    invitarTitulo: "Invitar a alguien",
    invitarTexto: "Escribí el correo con el que se va a registrar. Si ya tiene cuenta, entra en el acto.",
    correo: "Correo",
    invitar: "Invitar",
    invitando: "Invitando…",
    invitado: "Invitación lista. Avisale a {{correo}} que se registre con ese correo.",
    entroYa: "{{correo}} ya tenía cuenta: entró al club.",
    yaEsta: "Esa cuenta ya está en el club.",
    invitacionesTitulo: "Invitaciones abiertas",
    vacioInvitaciones: "No hay invitaciones esperando.",
    venceEl: "Vence el {{fecha}}",
    invitacionesVencidasTitulo: "Invitaciones vencidas",
    vencida: "Vencida",
    vencioEl: "Venció el {{fecha}}: para que entre, invitalo de nuevo",
    copiarMensaje: "Copiar mensaje",
    copiado: "Mensaje copiado. Pegalo en WhatsApp o en un correo.",
    mensajeInvitacion: "Te invité a {{club}} en Registro Partido. Entrá a {{enlace}} y creá tu cuenta con este correo: {{correo}}.",
    cancelarInvitacion: "Cancelar",
    invitacionCancelada: "Invitación cancelada.",
    miembrosTitulo: "En el club",
    exMiembrosTitulo: "Se fueron",
    vacioMiembros: "Todavía no hay nadie en el club.",
    vacioExMiembros: "Nadie se fue del club.",
    desdeEl: "En el club desde el {{fecha}}",
    hastaEl: "Hasta el {{fecha}} · solo lectura",
    roles: {
      admin: "Administrador del club",
      staff: "Staff",
    },
    modulos: {
      partido: "Partido",
      flujo: "Flujo diario",
      lesiones: "Lesiones",
      evaluaciones: "Evaluaciones",
    },
    ningunModulo: "ningún módulo",
    darBaja: "Dar de baja",
    reincorporar: "Reincorporar",
    reincorporado: "{{correo}} volvió al club.",
    dadoDeBaja: "{{correo}} dejó el club. Ve lo cargado hasta su último día.",
    verHistoria: "Historia",
    historiaTitulo: "{{correo}} en {{club}}",
    sinHistoria: "Todavía no hay movimientos.",
    porQuien: "por {{correo}}",
    movimientos: {
      alta: "Entró al club ({{rol}}; {{modulos}})",
      baja: "Dejó el club: último día {{fecha}}",
      reincorporacion: "Volvió al club",
      rol: "Pasó a {{rol}}",
      modulos: "Módulos: {{modulos}}",
      borrado: "Se borró la membresía",
    },
    bajaTitulo: "¿Cuál fue su último día en el club?",
    bajaTexto: "{{correo}} va a seguir viendo lo cargado en {{club}} hasta ese día, sin poder cambiar nada.",
    bajaFecha: "Último día en el club",
    siBaja: "Sí, dar de baja",
    cuentaBloqueada: "Cuenta bloqueada",
    cuentaPendiente: "Cuenta pendiente",
    porAutorizar: "Por autorizar",
    conAcceso: "Con acceso",
    sinAcceso: "Sin acceso",
    vacioPendientes: "No hay cuentas esperando autorización.",
    vacioConAcceso: "Todavía no hay cuentas con acceso.",
    vacioSinAcceso: "No hay cuentas sin acceso.",
    tuCuenta: "Tu cuenta",
    dueno: "Dueño de la app",
    correoSinConfirmar: "Correo sin confirmar",
    creadaEl: "Creada el {{fecha}}",
    sinClub: "Sin club",
    clubAdmin: "{{club}} (administra)",
    clubHasta: "{{club}} (hasta el {{fecha}})",
    sumarA: "Sumar a {{club}}",
    devolverAcceso: "Devolver acceso",
    rechazar: "Rechazar",
    quitarAcceso: "Quitar acceso",
    quePuedeUsar: "Qué puede usar {{correo}}",
    rechazarTitulo: "¿Rechazar esta cuenta?",
    quitarTitulo: "¿Quitar el acceso?",
    rechazarTexto: "{{correo}} no va a poder entrar a la app. Si cambiás de idea, le podés devolver el acceso desde Sin acceso.",
    quitarTexto: "{{correo}} deja de entrar a la app y a todos sus clubes en el momento. Sus clubes no se tocan: si le devolvés el acceso, vuelve a lo que tenía.",
    siRechazar: "Sí, rechazar",
    siQuitar: "Sí, quitar",
    laCuenta: "La cuenta",
    sinCorreo: "(sin correo)",
    errorLeer: "No se pudieron leer las cuentas.",
    errorCambiar: "No se pudo cambiar la cuenta.",
    errorCambiarSinPermiso: "No se pudo guardar el cambio: no tenés permiso o la cuenta ya no existe.",
    errorClubes: "No se pudo leer la gente del club.",
    errorClub: "No se pudo cambiar la membresía.",
    errorUltimoAdmin: "Es el último administrador del club: nombrá a otro antes.",
    errorHastaFutura: "El último día no puede ser una fecha futura.",
    errorCorreo: "Escribí un correo válido.",
    errorInvitacionRepetida: "Ya hay una invitación abierta para ese correo.",
    errorSinPermiso: "No tenés permiso para hacer eso.",
    errorFaltaMigracion: "Falta actualizar la base (cuentas v2). Pedile al administrador que corra la migración.",
    errorHistorial: "No se pudo leer la historia.",
    errorInvitaciones: "No se pudieron leer las invitaciones.",
    errorInvitar: "No se pudo guardar la invitación.",
  },
  lesiones: {
    titulo: "Lesiones",
    hoy: "Lesionados hoy",
    activas_one: "{{n}} lesión activa",
    activas_other: "{{n}} lesiones activas",
    sinActivas: "No hay lesiones activas. Todo el plantel está disponible.",
    nueva: "Nueva lesión",
    pasos: {
      dados_geraisTexto: "¿Quién se lesionó? Buscá al jugador por el nombre.",
      descricao_geralTexto: "Qué tipo de lesión fue y dónde: en la figura, primero la zona y después la parte. La imagen, si ya la hay.",
      descricao_especificaTexto: "Ligamento o músculo, si ya se sabe. Se puede completar después.",
      descricao_contextualTexto: "Cómo, cuándo y dónde pasó.",
      evolucaoTexto: "La fecha de inicio, y las de transición, retorno y alta cuando las haya.",
      observacoesTexto: "Lo que haga falta anotar.",
      paso: "Paso {{n}} de {{total}}",
      siguiente: "Siguiente",
      atras: "Atrás",
      guardar: "Guardar la lesión",
      buscar: "Buscar jugador...",
      ningunJugador: "Ningún jugador con ese nombre.",
      cambiar: "Cambiar",
      sinJugador: "Elegí al jugador para seguir.",
      opcional: "Opcional",
    },
    darAlta: "Alta médica",
    borrar: "Borrar lesión",
    borrarTitulo: "¿Borrar esta lesión?",
    borrarTexto: "Se borra la lesión de {{jugador}}. Queda anotado en el historial de cambios.",
    siBorrar: "Sí, borrar",
    salirTitulo: "¿Salir sin guardar?",
    salirTexto: "Lo que cargaste en esta lesión se pierde.",
    siSalir: "Sí, salir",
    seguirCargando: "Seguir cargando",
    borrada: "Lesión borrada",
    editar: "Editar",
    verDetalle: "Ver detalle",
    caso: "Caso {{n}}",
    dias_one: "{{n}} día",
    dias_other: "{{n}} días",
    horas_one: "{{n}} hora",
    horas_other: "{{n}} horas",
    anios_one: "{{n}} año",
    anios_other: "{{n}} años",
    desde: "desde el {{fecha}}",
    altaEl: "alta el {{fecha}}",
    etapa: {
      lesionado: "Lesionado",
      transicion: "En transición",
      entrenando: "Entrenando",
      alta: "Con alta",
      sinFecha: "Sin fecha de inicio",
    },
    fueraDeDatos: "No está en Datos básicos",
    sinFecha: {
      titulo_one: "{{n}} lesión sin fecha de inicio",
      titulo_other: "{{n}} lesiones sin fecha de inicio",
      texto: "Vinieron así del Excel. No cuentan como activas, ni en días perdidos, ni en los reportes hasta que se complete la fecha: abrí cada una y editala.",
    },
    altaTitulo: "¿Dar el alta médica?",
    altaTexto: "{{jugador}} vuelve a competir desde la fecha que elijas.",
    altaFecha: "Retorno a la competencia",
    siAlta: "Sí, dar el alta",
    formNueva: "Nueva lesión",
    formEditar: "Editar lesión",
    sinJugadores: "No hay jugadores cargados. Se agregan en Datos básicos.",
    guardado: "Lesión guardada",
    altaGuardada: "Alta guardada",
    avisoRecidiva: "Ojo: ya tuvo una lesión en {{parte}} ({{lado}}) el {{fecha}}. Puede contar como recurrencia o recidiva.",
    graficos: {
      opcion: "Informes gráficos",
      opcionTexto: "Los gráficos del plantel: lesiones y días perdidos c/1000 h de los períodos guardados, partes del cuerpo, lesiones por jugador y entrenamiento y partidos",
      titulo: "INFORMES GRÁFICOS DE LESIONES",
      alDia: "Al {{fecha}}",
      ir: "Ir a",
      filtros: "Filtros",
      secciones: {
        lesiones: "N° de lesiones c/1000 h",
        dias: "N° de días perdidos c/1000 h",
        partes: "Partes del cuerpo",
        jugador: "Lesiones por jugador",
        momentos: "Entrenamiento y partidos",
      },
      anio: "Año",
      todosLosAnios: "Todos los años",
      anioNota: {
        hasta: "El año de cada período es el de su fecha final.",
        desde: "El año de cada período es el de su fecha de inicio.",
      },
      sinPeriodos: "Todavía no hay períodos guardados. Se guardan en «Lesiones c/1000h y días perdidos».",
      sinPeriodosDelAnio: "No hay períodos guardados de {{anio}}.",
      irAPeriodos: "Guardar períodos",
      todos: "Todos",
      filtro: "{{campo}}: {{valor}}",
      sinDato: "Sin dato",
      sinLesiones: "No hay lesiones con estos filtros.",
      cuentanTodas: "Cuentan todas las lesiones con fecha de inicio y «{{campo}}» cargado, de cualquier fecha.",
      elegidos_one: "{{n}} elegido",
      elegidos_other: "{{n}} elegidos",
      cuentanConSerie: "Cuentan las lesiones con fecha de inicio, «{{contado}}» y «{{campo}}» cargados, de cualquier fecha.",
      cuentanMomentos: "Cuentan las lesiones con fecha de inicio, «{{contado}}» y «{{campo}}» cargados, por el año de la fecha de inicio.",
    },
    cadaMil: {
      opcion: "Lesiones c/1000h y días perdidos",
      opcionTexto: "Elegí las fechas: lesiones y días perdidos del período, los minutos de entrenamiento y cada 1000 horas. Guardalo con un nombre para compararlo",
      titulo: "LESIONES C/1000 H Y DÍAS PERDIDOS",
      elegir: "Elegí la fecha de inicio, la final y un nombre para el período",
      baseCompleta: "Base completa",
      inicio: "Inicio",
      final: "Final",
      sinInicio: "Sin inicio: desde la primera lesión.",
      nombre: "Nombre del período",
      nombreEjemplo: "Ej.: Primer semestre",
      minutos: "Minutos de entrenamiento",
      horas: "Horas de entrenamiento",
      resultado: "Lesiones y días perdidos del período",
      nLesiones: "N° de lesiones",
      nDias: "N° de días perdidos",
      faltaGps: "Faltan los minutos del GPS: las cuentas cada 1000 horas aparecen cuando la base del GPS esté en la app.",
      guardar: "Guardar el período",
      yaGuardado: "Período guardado",
      guardado: "Período guardado",
      faltaNombre: "Falta el nombre del período.",
      faltaFinal: "Elegí la fecha final.",
      guardados: "Períodos guardados",
      sinGuardados: "Todavía no hay períodos guardados. Elegí las fechas, ponele un nombre y guardalo para compararlo después.",
      borrar: "Borrar el período {{nombre}}",
      borrarTitulo: "¿Borrar el período?",
      borrarTexto: "«{{nombre}}» sale de la lista de períodos guardados. Las lesiones no se tocan.",
      borrado: "Período borrado",
    },
    periodos: {
      error: {
        noLeer: "No se pudieron leer los períodos guardados.",
        noGuardar: "No se pudo guardar el período.",
        noBorrar: "No se pudo borrar el período.",
        repetido: "Ya hay un período con ese nombre.",
        fechas: "La fecha de inicio no puede ser posterior a la final.",
        nombre: "Escribí un nombre de hasta 80 letras.",
        faltaMigracion: "Para guardar períodos falta correr en Supabase el SQL de los períodos (20261009_lesiones_periodos.sql).",
      },
    },
    importar: {
      boton: "Pegar desde Excel",
      titulo: "Pegar lesiones desde Excel",
      texto: "En el Excel, en la hoja Antecedentes BD, copiá la tabla desde la fila de cabeceras (la que dice N° de Caso, Nome e Sobrenome…) hasta la última lesión, y pegala acá. Antes de cargar se ve qué pasa con cada fila. Entran todas: las que no tienen fecha de inicio quedan para completar.",
      pegarAca: "Pegá acá lo que copiaste del Excel",
      borrar: "Borrar lo pegado",
      sinCabeceras: "No encontré la fila de cabeceras. Copiá la tabla junto con la fila que dice Nome e Sobrenome.",
      sinFilas: "Debajo de las cabeceras no hay lesiones.",
      filas_one: "{{n}} fila en lo pegado",
      filas_other: "{{n}} filas en lo pegado",
      nuevas_one: "{{n}} para cargar",
      nuevas_other: "{{n}} para cargar",
      yaEstan_one: "{{n}} ya está en la app",
      yaEstan_other: "{{n}} ya están en la app",
      sinFechas_one: "{{n}} sin fecha de inicio",
      sinFechas_other: "{{n}} sin fecha de inicio",
      conProblemas_one: "{{n}} con problemas",
      conProblemas_other: "{{n}} con problemas",
      porElegir_one: "{{n}} para elegir",
      porElegir_other: "{{n}} para elegir",
      noVan_one: "{{n}} no se carga",
      noVan_other: "{{n}} no se cargan",
      fueraDeDatos_one: "{{n}} nombre no está en Datos básicos: tocalo para elegir qué hacer, o guardalo igual.",
      fueraDeDatos_other: "{{n}} nombres no están en Datos básicos: tocá cada uno para elegir qué hacer, o guardalos igual.",
      guardarTodasIgual_one: "Guardar igual la que no está en Datos básicos",
      guardarTodasIgual_other: "Guardar igual las {{n}} que no están en Datos básicos",
      quienEs: "¿Qué hacemos con {{nombre}}?",
      comoPersona: "Guardar con este nombre (no se agrega a Datos básicos)",
      noCargar: "No cargar",
      es: "Es {{jugador}}",
      seGuardaComoPersona: "No está en Datos básicos: la lesión se guarda con este nombre y el nombre no se agrega a Datos básicos.",
      seGuardaComo: "No está en Datos básicos: la lesión se guarda como {{nombre}}, escrito como en otra lesión de la misma persona, y el nombre no se agrega a Datos básicos.",
      faltaCompletar: "Se carga sin {{columnas}}: queda para completar.",
      caso: "Caso {{n}}",
      sinCaso: "Sin N° de caso",
      estado: {
        nueva: "Se carga",
        yaEsta: "Ya está en la app",
        sinJugador: "No está en Datos básicos",
        dudoso: "¿Quién es?",
        comoPersona: "Se guarda con este nombre",
        noVa: "No se carga",
        conProblemas: "No se carga",
      },
      sinJugador: "Este nombre no está en Datos básicos. Elegí si se guarda con este nombre (no se agrega a Datos básicos), si es un jugador de la lista o si no se carga.",
      jugadorDudoso: "En Datos básicos hay más de un jugador con un nombre así: elegí cuál es, o guardalo con este nombre.",
      casoOcupado: "Ya hay otra lesión con este N° de caso en la app.",
      casoRepetido: "Este N° de caso está dos veces en lo pegado.",
      nombreLargo: "El nombre es demasiado largo para guardarlo (hasta 120 letras).",
      sinNombre: "Falta el nombre: no se sabe de quién es.",
      sinNombreFila: "Sin nombre",
      plantelSinLeer: "No se pudo leer Datos básicos, y sin eso no se sabe quién es cada uno. Volvé y probá de nuevo.",
      quedanSinElegir_one: "{{n}} nombre sigue sin elegir: esa lesión no se carga hasta que elijas qué hacer.",
      quedanSinElegir_other: "{{n}} nombres siguen sin elegir: esas lesiones no se cargan hasta que elijas qué hacer.",
      aviso: "«{{valor}}» no se entendió en {{columna}}: queda vacío.",
      cargar_one: "Cargar {{n}} lesión",
      cargar_other: "Cargar {{n}} lesiones",
      nadaQueCargar: "Nada para cargar",
      cargando: "Cargando {{n}} de {{total}}…",
      listo_one: "Listo: se cargó {{n}} lesión.",
      listo_other: "Listo: se cargaron {{n}} lesiones.",
      fallaron_one: "{{n}} lesión no se pudo cargar:",
      fallaron_other: "{{n}} lesiones no se pudieron cargar:",
      fallo: "{{caso}} · {{nombre}}: {{error}}",
    },
    error: {
      jugador: "Elegí un jugador.",
      fecha: "Cargá la fecha de inicio de la lesión.",
      fechaFutura: "La fecha de inicio no puede ser futura.",
      fechaAntes: "Las fechas de transición, retorno y alta no pueden ser anteriores al inicio.",
      fechaFuturaOtra: "Ninguna fecha puede ser futura.",
      parte: "Elegí la parte del cuerpo lesionada.",
      lado: "Elegí el lado.",
      tipo: "Elegí el tipo de lesión.",
      imagen: "La hora de la imagen no es válida.",
      imagenAntes: "La imagen no puede ser de antes del día de la lesión.",
      lesionDespuesDeImagen: "La lesión no puede empezar después de la imagen ({{imagen}}).",
      solapada: "Ya hay una lesión activa en {{parte}} ({{lado}}) para este jugador.",
      repetida: "Esa lesión ya está cargada: este jugador ya tiene una en {{parte}} ({{lado}}) que empieza el mismo día.",
      noGuardar: "No se pudo guardar la lesión.",
      noBorrar: "No se pudo borrar la lesión.",
      noLeer: "No se pudieron leer las lesiones.",
      faltaMigracion: "La base todavía no tiene las tablas de lesiones: falta ejecutar la migración 20261002_lesiones_excel.sql en Supabase.",
      faltaMigracionPersonas: "Para guardar lesiones sin fecha de inicio o de alguien que no está en Datos básicos falta correr en Supabase el SQL 20261010_lesiones_sin_fecha_y_personas.sql.",
      sinPermiso: "Tu cuenta no tiene permiso para cargar lesiones.",
    },
    reportes: {
      titulo: "Reportes",
      texto: "Lo que muestran las lesiones cargadas, de un jugador o del plantel.",
      ver: "Ver reportes",
      individual: "Reporte individual",
      individualTexto: "Un jugador: lesiones y días perdidos cada 1000 horas contra la referencia del plantel, su mapa corporal y su historial",
      grupal: "Reporte grupal",
      grupalTexto: "El plantel: cada 1000 horas, meses, zonas, tipos y quiénes perdieron más días",
      crear: "Crear reportes",
      crearTexto: "Lo próximo: armar tus propios reportes con bloques (un gráfico, una tabla o un número), eligiendo qué medir, cómo separarlo y con qué filtros, y guardarlos para el club.",
      individualTitulo: "Reporte individual de lesiones",
      grupalTitulo: "REPORTE GRUPAL DE LESIONES",
      volver: "Reportes",
      imprimir: "Imprimir o guardar en PDF",
      elegirJugador: "¿De qué jugador?",
      cambiarJugador: "Cambiar jugador",
      periodo: "Período",
      periodos: {
        anio: "Este año",
        doce: "Últimos 12 meses",
        todo: "Todo",
        medida: "Elegir fechas",
      },
      desde: "Desde",
      hasta: "Hasta",
      cuales: "Qué lesiones",
      sinLeves: "Sin leves",
      soloMusculares: "Solo LM",
      todas: "Todas las lesiones",
      nacimiento: "Nacimiento",
      pie: "Pie dominante",
      kpiLesiones: "Lesiones",
      kpiDias: "Días perdidos",
      kpiActivas: "Abiertas hoy",
      kpiJugadores: "Jugadores lesionados",
      kpiPromedio: "Días por lesión (con alta)",
      kpiRecurrentes: "Recurrentes",
      cadaMil: "Cada 1000 horas",
      lesionesMil: "Lesiones c/ 1000 h",
      diasMil: "Días perdidos c/ 1000 h",
      tiposTodos: "Tipos (TODOS)",
      tiposLM: "Tipos (SOLO LM)",
      severidadTodas: "Severidad (TODAS)",
      severidadSinLeves: "Severidad (SIN LEVES)",
      indicadores: "Indicadores de lesión",
      tasas: "Tasas por 1000 horas",
      variante: "{{severidad}} y {{tipos}}",
      referencia: "Referencia",
      comparado: {
        peor: "Superior a la referencia",
        mejor: "Inferior a la referencia",
        igual: "Igual a la referencia",
      },
      superiorRef: "Superior a la referencia",
      inferiorRef: "Inferior a la referencia",
      queEsRef: "Referencia = el valor del plantel (VR)",
      porcentajeVsRef: "{{valor}} vs referencia",
      lesionesPorMil: "Lesiones",
      diasPorMil: "Días perdidos",
      porMil: "/ 1000 h",
      unidadLesiones: "lesiones / 1000 h",
      unidadDias: "días / 1000 h",
      mapaCorporal: "Mapa corporal de lesiones",
      vistas: {
        frente: "Anterior",
        espalda: "Posterior",
      },
      mapaNota: "Cuanto más grande e intensa la mancha, más lesiones en ese lugar. Derecha e izquierda son las del jugador.",
      historialLesiones: "Historial de lesiones",
      registros_one: "{{n}} registro",
      registros_other: "{{n}} registros",
      cuentan: "Cuentan las lesiones con {{criterio}}.",
      cuentanLm: "En «{{lm}}», de esas, las de tipo {{tipos}}.",
      faltaGps: "Faltan los minutos del GPS: sin ellos no se pueden sacar las cuentas cada 1000 horas.",
      sinLesionesJugador: "No tiene lesiones cargadas.",
      sinLesiones: "No hay lesiones en este período con estos filtros.",
      dondeSeLesionan: "Dónde se lesionan",
      abierta: "Sin alta",
      porMes: "Lesiones por mes",
      masDias: "Quiénes perdieron más días",
    },
    historial: {
      titulo: "Historial individual",
      texto: "Elegí un jugador y mirá todas sus lesiones, como en la base.",
      buscar: "Buscar un jugador...",
      sinLesiones: "Este jugador no tiene lesiones cargadas.",
      cantidad_one: "{{n}} lesión",
      cantidad_other: "{{n}} lesiones",
    },
    cuerpo: {
      figura: "Figura del cuerpo",
      donde: "Dónde fue la lesión",
      cuerpo: "Cuerpo",
      vista: "Cómo mirar la figura",
      frente: "De frente",
      espalda: "De espaldas",
      derecha: "DERECHA",
      izquierda: "IZQUIERDA",
      tocaZona: "Tocá la zona de la lesión.",
      regiones: {
        cabeza: "Cabeza y cuello",
        tronco: "Tronco",
        brazo_derecho: "Brazo derecho",
        brazo_izquierdo: "Brazo izquierdo",
        pierna_derecha: "Pierna derecha",
        pierna_izquierda: "Pierna izquierda",
      },
      queLado: "¿De qué lado?",
      elegido: "{{parte}} · {{lado}}",
      ubicacion: "Ubicación",
      estructuraTexto: "Tocá lo que corresponda: están las opciones de las listas que van en esta parte del cuerpo.",
      estructuraFigura: "Tocá en la figura el músculo, el tendón o el ligamento, o elegilo abajo. Lo oscuro no está en las listas de esta parte.",
      capa: "Qué músculos mirar",
      capas: {
        superficie: "Superficiales",
        profunda: "Profundos",
      },
      esquemas: {
        rodilla: "Rodilla por dentro",
        tobilloAfuera: "Tobillo por fuera",
        tobilloAdentro: "Tobillo por dentro",
        planta: "Planta del pie",
      },
      rotulos: {
        lca: "LCA",
        lcp: "LCP",
        lle: "LLE",
        lli: "LLI",
        ml: "ML",
        mm: "MM",
        anterior: "Anterior",
        medio: "Medio",
        posterior: "Posterior",
        sindesmosis: "Sindesmosis",
        deltoideo: "Deltoideo",
        musculos: "Músculos",
        aductor: "Aductor",
        fascia: "Fascia",
        insercion: "Inserción",
      },
      leyenda: {
        musculos: "Músculos",
        tendones: "Tendones",
        ligamentos: "Ligamentos",
      },
      sinEstructuras: "En las listas no hay músculos ni ligamentos para esta parte del cuerpo.",
      tercios: {
        proximal: "Proximal",
        medio: "Medio",
        distal: "Distal",
      },
      deLaLista: "Elegir de la lista",
      conFigura: "Elegir con la figura",
    },
    ficha: {
      resumen: "Resumen de la lesión",
      secciones: "Qué mirar",
      diasDeBaja: "Días de baja",
      cambios: "Cambios",
      ultimos: "Últimos cambios",
      ultimosTexto: "Los 5 más recientes",
      sinCambios: "Sin cambios registrados.",
      cambio: "{{fecha}} · {{quien}}",
      creada: "Carga",
      editada: "Edición",
      columnas: "Cambió: {{columnas}}",
    },
    ajustes: {
      titulo: "Ajustes",
      texto: "Lo que la app usa en Lesiones.",
      cabeceras: "Cabeceras",
      cabecerasTexto: "Cómo se llama cada columna del Excel",
      cabecerasAyuda: "Tocá un grupo o una columna para cambiarle el nombre en cada idioma. Las columnas también se pueden esconder del formulario.",
      listas: "Listas",
      listasTexto: "Las opciones de cada desplegable",
      listasAyuda: "Tocá una lista para agregar, renombrar o esconder opciones. Lo que ya está cargado no se pierde.",
      volver: "Volver a Ajustes",
      volverListas: "Volver a Listas",
      editarCabecera: "Cabecera",
      editarGrupo: "Grupo",
      grupoDe_one: "Grupo de {{n}} columna",
      grupoDe_other: "Grupo de {{n}} columnas",
      grupoAyuda: "Es la fila de arriba de las cabeceras: ordena la base, la carga por pasos y la ficha.",
      editarOpcion: "Opción",
      nuevaOpcion: "Agregar una opción",
      nombre: "Nombre en este idioma",
      nombreAyuda: "Para cambiarlo en otro idioma, cambiá el idioma de la app y volvé acá.",
      mostrar: "Se muestra",
      oculto: "Oculta",
      guardado: "Guardado",
      errorGuardar: "No se pudo guardar el cambio.",
      opciones_one: "{{n}} opción",
      opciones_other: "{{n}} opciones",
      porDefecto: "Del Excel: {{texto}}",
      faltaTexto: "Escribí el nombre.",
      noSeOculta: "Esta columna hace falta para registrar la lesión: siempre se muestra.",
      seUbicanSolas: "Las que agregues se ubican solas en el cuerpo, por su nombre.",
      vaEn: "En el cuerpo: {{partes}}",
      vaEnTodas: "No se reconoce en qué parte del cuerpo va: aparece en todas",
      vaConTercio: "Tercio: {{tercio}}",
      sinTercio: "Del músculo entero, sin tercio",
    },
    estado: {
      cargando: "Leyendo las lesiones…",
      sinConexion: "Sin conexión. Lesiones necesita señal para leer y guardar.",
    },
  },
};
