// Textos de la app en castellano rioplatense. Es el idioma de referencia: si
// a otro diccionario le falta una clave, se muestra lo que dice acá.
// Regla: texto nuevo = clave nueva acá Y en pt-BR.js (la prueba lo exige).
export default {
  comun: {
    cancelar: "Cancelar",
    volver: "Volver",
    guardar: "Guardar",
    guardando: "Guardando…",
    cerrar: "Cerrar",
    listo: "Listo",
    si: "Sí",
    no: "No",
    hoy: "Hoy",
    actualizar: "Actualizar",
    actualizando: "Actualizando…",
    reintentar: "Reintentar",
    cargando: "Cargando…",
    salir: "Salir",
    saliendo: "Saliendo…",
    sinConexion: "No hay conexión. Fijate la señal y probá de nuevo.",
    idioma: "Idioma",
    todos: "Todos",
    sinDato: "Sin dato",
    buscar: "Escribir para buscar...",
    sinCoincidencias: "Sin coincidencias.",
    elegir: "Elegí…",
    borrar: "Borrar",
    filtros: "Filtros",
    quitarFiltros: "Quitar filtros",
    cambiar: "Cambiar",
  },
  nav: {
    partido: "Partido",
    formacion: "Formación",
    registros: "Registros",
    ajustes: "Ajustes",
    inicio: "Inicio",
    tareas: "Tareas",
    lesionados: "Lesionados",
    historial: "Historial",
    base: "Base",
    jugadores: "Jugadores",
    reportes: "Reportes",
    posiciones: "Posiciones",
    catapult: "Catapult",
  },
  acceso: {
    marca: "Registro Partido",
    volverPortal: "Volver al portal",
    cargandoTitulo: "Un momento…",
    cargandoTexto: "Estamos comprobando tu cuenta.",
    cargandoTarda: "Está tardando más de lo normal. Si no tenés señal, puede demorar hasta medio minuto.",
    recuperarTitulo: "Elegí una contraseña nueva",
    recuperarTexto: "De ahora en más vas a entrar con esta contraseña.",
    nuevaContrasena: "Nueva contraseña",
    repetirContrasena: "Repetir contraseña",
    guardarContrasena: "Guardar contraseña",
    pendienteTitulo: "Tu cuenta está pendiente de autorización",
    pendienteTexto: "La cuenta {{correo}} ya está creada. Si te invitaron a un club, confirmá este correo (te llegó un mail) y tocá Volver a comprobar. Si no, pedile al administrador de tu club que te invite con este correo.",
    bloqueadoTitulo: "Tu cuenta no tiene acceso",
    bloqueadoTexto: "El administrador le quitó el acceso a esta cuenta. Si creés que es un error, hablá con él.",
    sinModulosTitulo: "Tu cuenta no tiene módulos habilitados",
    sinModulosTexto: "El administrador todavía no te habilitó ningún módulo. Cuando lo haga, tocá Volver a comprobar.",
    comprobar: "Volver a comprobar",
    comprobando: "Comprobando…",
    noPudimosTitulo: "No pudimos comprobar tu cuenta",
    noPudimosTexto: "Probá de nuevo en un momento.",
    entrarTitulo: "Entrá con tu cuenta",
    entrarTexto: "Usá el correo y la contraseña con los que te registraste.",
    correo: "Correo",
    contrasena: "Contraseña",
    correoEjemplo: "nombre@club.com",
    entrar: "Entrar",
    entrando: "Entrando…",
    olvide: "Olvidé mi contraseña",
    enviando: "Enviando…",
    crear: "Crear una cuenta",
    creando: "Creando…",
    notaAutorizacion: "Las cuentas nuevas necesitan la autorización del administrador antes de poder entrar.",
    error: {
      credenciales: "El correo o la contraseña no son correctos.",
      noConfirmado: "Todavía no confirmaste tu correo. Buscá el mensaje en tu casilla (también en spam).",
      yaRegistrado: "Ese correo ya tiene una cuenta. Entrá con tu contraseña o pedí una nueva.",
      demasiados: "Hubo demasiados intentos seguidos. Esperá unos minutos y probá de nuevo.",
      mismaContrasena: "La contraseña nueva tiene que ser distinta de la anterior.",
      debil: "La contraseña es muy fácil de adivinar. Usá al menos 8 caracteres, mezclando letras y números.",
      reautenticar: "Por seguridad, pedí un enlace nuevo desde Olvidé mi contraseña y probá otra vez.",
      enlaceVencido: "El enlace del correo venció o ya se usó. Pedí uno nuevo.",
      enlaceInvalido: "El enlace del correo no es válido. Pedí uno nuevo.",
      enlaceRecuperacion: "El enlace de recuperación no es válido o ya venció. Pedí uno nuevo desde Olvidé mi contraseña.",
      enlaceNoValido: "El enlace de recuperación no es válido. Pedí uno nuevo.",
      minimo8: "La contraseña nueva tiene que tener al menos 8 caracteres.",
      noCoinciden: "Las contraseñas no coinciden.",
      sesionNoAbierta: "No se pudo abrir la sesión después de cambiar la contraseña.",
      sinConexionCuenta: "No hay conexión y no pudimos comprobar tu cuenta. Probá de nuevo cuando tengas señal.",
      noComprobar: "No se pudo comprobar tu cuenta. Probá de nuevo.",
      noEntrar: "No se pudo entrar. Probá de nuevo.",
      completar: "Completá el correo y la contraseña.",
      noCrear: "No se pudo crear la cuenta.",
      escribiCorreo: "Primero escribí tu correo, así te mandamos el enlace.",
      noEnviarCorreo: "No se pudo enviar el correo de recuperación.",
      noCambiarContrasena: "No se pudo cambiar la contraseña.",
    },
    cuentaCreada: "Cuenta creada. Te mandamos un correo para confirmarla: abrí el enlace y volvé a entrar. Después el administrador tiene que autorizarla.",
    enlaceEnviado: "Si ese correo tiene una cuenta, te va a llegar un enlace para elegir una contraseña nueva. Revisá también la carpeta de spam.",
  },
  portal: {
    pregunta: "¿Qué vas a hacer hoy?",
    elegi: "Elegí por dónde arrancar.",
    unSolo: "Por ahora tenés habilitado este módulo.",
    cuentas: "Cuentas",
    modulos: "Módulos",
    salir: "Salir",
    entrar: "Entrar",
    entrarA: "Entrar a {{modulo}}",
    entrando: "Entrando…",
    enPrueba: "En prueba",
    nuevo: "Nuevo",
    partidoTitulo: "Partido",
    partidoTexto: "Registrá el partido en vivo: formación, tiempos y cambios.",
    flujoTitulo: "Flujo diario",
    flujoTexto: "Todo lo del día después de entrenar: cortes, datos, planilla y PSE.",
    lesionesTitulo: "Lesiones",
    lesionesTexto: "Quién está lesionado, desde cuándo y cuándo vuelve. Carga en cuatro toques.",
    datosTitulo: "Datos básicos",
    datosTexto: "Los jugadores y sus datos, en una tabla que se copia y se pega como en Excel.",
  },
  tabla: {
    copiar: "Copiar",
    pegar: "Pegar",
    ficha: "Ver ficha",
    borrarFila: "Borrar fila",
    sinSeleccion: "Tocá una celda para empezar. Mantené apretada una cabecera para moverla.",
    seleccion_one: "{{n}} celda elegida",
    seleccion_other: "{{n}} celdas elegidas",
    copiado_one: "{{n}} celda copiada",
    copiado_other: "{{n}} celdas copiadas",
    pegado_one: "{{n}} celda pegada",
    pegado_other: "{{n}} celdas pegadas",
    ignoradas_one: "{{n}} no se entendió o no se puede cambiar",
    ignoradas_other: "{{n}} no se entendieron o no se pueden cambiar",
    horasMalEscritas: "Las horas se escriben como en el Excel: 30:14:20, 30:14 o 30,5.",
    nadaQuePegar: "No hay nada para pegar. Copiá celdas de Excel o de esta tabla.",
    sinPermisoPegar: "El celular no deja leer lo copiado. Pegá con Ctrl+V dentro de una celda.",
    editar: "Tocá dos veces una celda para cambiarla.",
    vacio: "Todavía no hay filas.",
    fila: "Fila",
    guardando: "Guardando…",
    filtrar: "Filtrar u ordenar {{columna}}",
    filtroTitulo: "Filtrar: {{columna}}",
    buscarValor: "Buscar…",
    todos: "Todos",
    ninguno: "Ninguno",
    vacias: "(Vacías)",
    ordenarAsc: "De menor a mayor",
    ordenarDesc: "De mayor a menor",
    quitarFiltro: "Quitar filtro",
    aplicar: "Aplicar",
    quitarFiltros: "Quitar filtros",
    mostrando: "Mostrando {{n}} de {{total}}",
    sinResultados: "Ninguna fila entra en los filtros.",
    nadaEnLista: "Ningún valor coincide.",
  },
  datos: {
    titulo: "Datos básicos",
    texto: "Los jugadores del club con lo que cada módulo necesita. Tocá una celda para elegirla, dos veces para cambiarla.",
    textoCorto: "Los jugadores del club con lo que cada módulo necesita.",
    agregar: "Agregar jugador",
    nombre: "Nombre y apellido",
    foto: "Foto (enlace)",
    horasPrevias: "Horas previas",
    agregado: "Jugador agregado",
    borrarTitulo: "¿Borrar al jugador?",
    borrarTexto: "{{jugador}} sale de la lista de jugadores de todos los módulos. Si tiene lesiones cargadas, no se puede.",
    siBorrar: "Sí, borrar",
    borrado: "Jugador borrado",
    guardado: "Guardado",
    jugadores_one: "{{n}} jugador",
    jugadores_other: "{{n}} jugadores",
    importar: {
      boton: "Pegar desde Excel",
      titulo: "Pegar desde Excel",
      texto: "En el Excel, copiá la tabla de Datos Básicos junto con la fila de cabeceras (Nome e Sobrenome, Categoria, D. Nac., P. Dominante, Posicao, Links das fotos) y pegala acá. Antes de cargar se ve qué pasa con cada jugador.",
      pegarAca: "Pegá acá lo que copiaste del Excel",
      borrar: "Borrar lo pegado",
      sinCabeceras: "No encontré la fila de cabeceras. Copiá la tabla junto con la fila que dice Nome e Sobrenome.",
      sinFilas: "Debajo de las cabeceras no hay jugadores.",
      jugadores_one: "{{n}} jugador en lo pegado",
      jugadores_other: "{{n}} jugadores en lo pegado",
      nuevos_one: "{{n}} nuevo",
      nuevos_other: "{{n}} nuevos",
      conCambios: "{{n}} con cambios",
      iguales: "{{n}} sin cambios",
      quienEs: "¿Quién es {{nombre}} en la app?",
      nuevo: "Jugador nuevo",
      noCargar: "No cargar",
      es: "Es {{jugador}}",
      pareceSer: "¿Es {{jugador}}?",
      repetido: "Repetido en lo pegado",
      trae: "Trae: {{columnas}}",
      cambia: "Cambia: {{columnas}}",
      sinCambios: "Ya tiene estos datos.",
      cambiaria: "Si es él, cambia: {{columnas}}",
      confirmar: "Sí, es {{jugador}}",
      porConfirmar_one: "{{n}} para confirmar",
      porConfirmar_other: "{{n}} para confirmar",
      sinDatos: "Solo el nombre.",
      aviso: "«{{valor}}» no se entendió en {{columna}}: queda como está.",
      cargar_one: "Cargar {{n}} jugador",
      cargar_other: "Cargar {{n}} jugadores",
      nadaQueCargar: "Nada para cargar",
      cargando: "Cargando {{n}} de {{total}}…",
      listo: "Listo: {{nuevos}} y {{actualizados}}.",
      actualizados_one: "{{n}} actualizado",
      actualizados_other: "{{n}} actualizados",
      fallaron_one: "{{n}} jugador no se pudo cargar:",
      fallaron_other: "{{n}} jugadores no se pudieron cargar:",
      fallo: "{{nombre}}: {{error}}",
      sinDatosGuardados: "se agregó, pero sus datos no se guardaron ({{error}})",
    },
    error: {
      nombre: "Escribí el nombre.",
      repetido: "Ese jugador ya está en la lista.",
      guardar: "No se pudo guardar.",
      leer: "No se pudieron leer los jugadores.",
      horas: "Las horas se escriben como en el Excel: 30:14:20, 30:14 o 30,5.",
      faltanHorasPrevias: "Para guardar las horas previas falta correr en Supabase el SQL de las horas previas.",
    },
    vacio: "Todavía no hay jugadores cargados.",
    posiciones: {
      titulo: "Dónde juega cada uno",
      texto: "Los puestos y los roles que usa Partido para armar la formación.",
      buscar: "Buscar jugador",
      nadie: "Ningún jugador con ese nombre.",
      agregarPuesto: "Agregar puesto",
      quitarPuesto: "Quitar este puesto",
    },
    puestos: {
      LAT: "Lateral",
      CAR: "Carrilero",
      DEF: "Defensor",
      VD: "Volante defensivo",
      VC: "Volante central",
      VM: "Volante mixto",
      VOL: "Volante",
      VO: "Volante ofensivo",
      EXT: "Extremo",
      MP: "Mediapunta",
      DEL: "Delantero",
    },
    roles: {
      Defensa: "Defensa",
      Mediocampo: "Mediocampo",
      Ataque: "Ataque",
    },
    catapult: {
      titulo: "Chalecos de Catapult",
      texto: "Cada jugador se empareja una vez con su chaleco para que los datos de Flujo diario lleguen a la persona correcta.",
      noLeer: "No se pudo leer la lista de jugadores.",
      noChalecos: "No se pudieron leer los chalecos.",
      conChaleco: "{{n}} con chaleco",
      chaleco: "Chaleco: {{chaleco}}",
      chalecoDe: "Chaleco de {{jugador}}",
      sinChaleco: "Sin chaleco",
      opcionSin: "— Sin chaleco —",
      repetido: "Repetido",
      yaNoExiste: "Ese chaleco ya no existe",
      guardado: "Guardado",
      exacto: "Coincide solo",
      probable: "Parecido, revisalo",
      aMano: "Elegido a mano",
      emparejar: "Emparejar con los chalecos",
      emparejarTexto: "Busca los chalecos de las últimas sesiones y propone quién es quién. Después guardás.",
      buscar: "Buscar chalecos",
      buscando: "Buscando…",
      resumen: "Chalecos encontrados: {{chalecos}} · coinciden solos: {{exactos}} · parecidos: {{probables}} · sin propuesta: {{sinPropuesta}} · ya no existen: {{ausentes}}",
      hayRepetidos: "Hay un chaleco elegido para más de un jugador. Corregilo antes de guardar.",
      sinCambios: "Sin cambios para guardar",
      guardar_one: "Guardar {{n}} cambio",
      guardar_other: "Guardar {{n}} cambios",
      guardados_one: "{{n}} cambio guardado.",
      guardados_other: "{{n}} cambios guardados.",
    },
  },
  club: {
    titulo: "¿Con qué club trabajás?",
    texto: "Elegí el club. Después lo podés cambiar desde el portal.",
    cargando: "Buscando los clubes…",
    vacio: "Todavía no estás en ningún club. Pedile al administrador de tu club que te invite con tu correo: {{correo}}.",
    vacioDueno: "Todavía no hay clubes. Creá el primero.",
    error: "No se pudieron leer los clubes.",
    crear: "Crear un club",
    nombre: "Nombre del club",
    crearBoton: "Crear y elegir",
    creando: "Creando…",
    cambiar: "Cambiar de club",
    elegido: "Club",
    hasta: "Hasta el {{fecha}} · solo lectura",
    sinMembresia: "No estás en este club",
    soloLecturaTitulo: "Dejaste este club el {{fecha}}.",
    soloLecturaTexto: "Ves lo cargado hasta ese día. No se puede agregar ni cambiar nada.",
    soloLecturaCambio: "Solo lectura: dejaste este club.",
  },
  openfield: {
    abriendoTitulo: "Un momento…",
    abriendoTexto: "Estamos conectando con OpenField.",
    sinAccesoTitulo: "Sin acceso a Flujo diario",
    errorTitulo: "No pudimos conectar con OpenField",
    errorTexto: "No se pudo abrir la sesión de OpenField. Probá de nuevo.",
    iniciaSesion: "Iniciá sesión para acceder a OpenField.",
  },
  cuentas: {
    kicker: "Administración",
    titulo: "Cuentas",
    texto: "Quién entra a cada club, con qué rol y qué módulos. Los cambios valen en el momento.",
    pestanaClub: "Gente del club",
    pestanaPlataforma: "Cuentas de la app",
    club: "Club",
    clubTexto: "Quien se va sigue viendo lo cargado hasta su último día, sin poder cambiar nada. Si vuelve, se lo reincorpora con la misma cuenta.",
    plataformaTexto: "Las cuentas de toda la app. A qué club entra cada una se decide desde la gente de cada club.",
    sinClubes: "No administrás ningún club.",
    invitarTitulo: "Invitar a alguien",
    invitarTexto: "Escribí el correo con el que se va a registrar. Si ya tiene cuenta, entra en el acto.",
    correo: "Correo",
    invitar: "Invitar",
    invitando: "Invitando…",
    invitado: "Invitación lista. Avisale a {{correo}} que se registre con ese correo.",
    entroYa: "{{correo}} ya tenía cuenta: entró al club.",
    yaEsta: "Esa cuenta ya está en el club.",
    invitacionesTitulo: "Invitaciones abiertas",
    vacioInvitaciones: "No hay invitaciones esperando.",
    venceEl: "Vence el {{fecha}}",
    copiarMensaje: "Copiar mensaje",
    copiado: "Mensaje copiado. Pegalo en WhatsApp o en un correo.",
    mensajeInvitacion: "Te invité a {{club}} en Registro Partido. Entrá a {{enlace}} y creá tu cuenta con este correo: {{correo}}.",
    cancelarInvitacion: "Cancelar",
    invitacionCancelada: "Invitación cancelada.",
    miembrosTitulo: "En el club",
    exMiembrosTitulo: "Se fueron",
    vacioMiembros: "Todavía no hay nadie en el club.",
    vacioExMiembros: "Nadie se fue del club.",
    desdeEl: "En el club desde el {{fecha}}",
    hastaEl: "Hasta el {{fecha}} · solo lectura",
    roles: {
      admin: "Administrador del club",
      staff: "Staff",
    },
    modulos: {
      partido: "Partido",
      flujo: "Flujo diario",
      lesiones: "Lesiones",
    },
    ningunModulo: "ningún módulo",
    darBaja: "Dar de baja",
    reincorporar: "Reincorporar",
    reincorporado: "{{correo}} volvió al club.",
    dadoDeBaja: "{{correo}} dejó el club. Ve lo cargado hasta su último día.",
    verHistoria: "Historia",
    historiaTitulo: "{{correo}} en {{club}}",
    sinHistoria: "Todavía no hay movimientos.",
    porQuien: "por {{correo}}",
    movimientos: {
      alta: "Entró al club ({{rol}}; {{modulos}})",
      baja: "Dejó el club: último día {{fecha}}",
      reincorporacion: "Volvió al club",
      rol: "Pasó a {{rol}}",
      modulos: "Módulos: {{modulos}}",
      borrado: "Se borró la membresía",
    },
    bajaTitulo: "¿Cuál fue su último día en el club?",
    bajaTexto: "{{correo}} va a seguir viendo lo cargado en {{club}} hasta ese día, sin poder cambiar nada.",
    bajaFecha: "Último día en el club",
    siBaja: "Sí, dar de baja",
    cuentaBloqueada: "Cuenta bloqueada",
    cuentaPendiente: "Cuenta pendiente",
    porAutorizar: "Por autorizar",
    conAcceso: "Con acceso",
    sinAcceso: "Sin acceso",
    vacioPendientes: "No hay cuentas esperando autorización.",
    vacioConAcceso: "Todavía no hay cuentas con acceso.",
    vacioSinAcceso: "No hay cuentas sin acceso.",
    tuCuenta: "Tu cuenta",
    dueno: "Dueño de la app",
    correoSinConfirmar: "Correo sin confirmar",
    creadaEl: "Creada el {{fecha}}",
    sinClub: "Sin club",
    clubAdmin: "{{club}} (administra)",
    clubHasta: "{{club}} (hasta el {{fecha}})",
    sumarA: "Sumar a {{club}}",
    devolverAcceso: "Devolver acceso",
    rechazar: "Rechazar",
    quitarAcceso: "Quitar acceso",
    quePuedeUsar: "Qué puede usar {{correo}}",
    rechazarTitulo: "¿Rechazar esta cuenta?",
    quitarTitulo: "¿Quitar el acceso?",
    rechazarTexto: "{{correo}} no va a poder entrar a la app. Si cambiás de idea, le podés devolver el acceso desde Sin acceso.",
    quitarTexto: "{{correo}} deja de entrar a la app y a todos sus clubes en el momento. Sus clubes no se tocan: si le devolvés el acceso, vuelve a lo que tenía.",
    siRechazar: "Sí, rechazar",
    siQuitar: "Sí, quitar",
    laCuenta: "La cuenta",
    sinCorreo: "(sin correo)",
    errorLeer: "No se pudieron leer las cuentas.",
    errorCambiar: "No se pudo cambiar la cuenta.",
    errorClubes: "No se pudo leer la gente del club.",
    errorClub: "No se pudo cambiar la membresía.",
    errorUltimoAdmin: "Es el último administrador del club: nombrá a otro antes.",
    errorHastaFutura: "El último día no puede ser una fecha futura.",
    errorCorreo: "Escribí un correo válido.",
    errorInvitacionRepetida: "Ya hay una invitación abierta para ese correo.",
    errorSinPermiso: "No tenés permiso para hacer eso.",
    errorFaltaMigracion: "Falta actualizar la base (cuentas v2). Pedile al administrador que corra la migración.",
    errorHistorial: "No se pudo leer la historia.",
    errorInvitaciones: "No se pudieron leer las invitaciones.",
    errorInvitar: "No se pudo guardar la invitación.",
  },
  lesiones: {
    titulo: "Lesiones",
    hoy: "Lesionados hoy",
    activas_one: "{{n}} lesión activa",
    activas_other: "{{n}} lesiones activas",
    sinActivas: "No hay lesiones activas. Todo el plantel está disponible.",
    nueva: "Nueva lesión",
    pasos: {
      dados_geraisTexto: "¿Quién se lesionó? Buscá al jugador por el nombre.",
      descricao_geralTexto: "Qué tipo de lesión fue y dónde: en la figura, primero la zona y después la parte. La imagen, si ya la hay.",
      descricao_especificaTexto: "Ligamento o músculo, si ya se sabe. Se puede completar después.",
      descricao_contextualTexto: "Cómo, cuándo y dónde pasó.",
      evolucaoTexto: "La fecha de inicio, y las de transición, retorno y alta cuando las haya.",
      observacoesTexto: "Lo que haga falta anotar.",
      paso: "Paso {{n}} de {{total}}",
      siguiente: "Siguiente",
      atras: "Atrás",
      guardar: "Guardar la lesión",
      buscar: "Buscar jugador...",
      ningunJugador: "Ningún jugador con ese nombre.",
      cambiar: "Cambiar",
      sinJugador: "Elegí al jugador para seguir.",
      opcional: "Opcional",
    },
    darAlta: "Alta médica",
    borrar: "Borrar lesión",
    borrarTitulo: "¿Borrar esta lesión?",
    borrarTexto: "Se borra la lesión de {{jugador}}. Queda anotado en el historial de cambios.",
    siBorrar: "Sí, borrar",
    borrada: "Lesión borrada",
    editar: "Editar",
    verDetalle: "Ver detalle",
    caso: "Caso {{n}}",
    dias_one: "{{n}} día",
    dias_other: "{{n}} días",
    horas_one: "{{n}} hora",
    horas_other: "{{n}} horas",
    anios_one: "{{n}} año",
    anios_other: "{{n}} años",
    desde: "desde el {{fecha}}",
    altaEl: "alta el {{fecha}}",
    etapa: {
      lesionado: "Lesionado",
      transicion: "En transición",
      entrenando: "Entrenando",
      alta: "Con alta",
    },
    altaTitulo: "¿Dar el alta médica?",
    altaTexto: "{{jugador}} vuelve a competir desde la fecha que elijas.",
    altaFecha: "Retorno a la competencia",
    siAlta: "Sí, dar el alta",
    formNueva: "Nueva lesión",
    formEditar: "Editar lesión",
    sinJugadores: "No hay jugadores cargados. Se agregan en Datos básicos.",
    guardado: "Lesión guardada",
    altaGuardada: "Alta guardada",
    avisoRecidiva: "Ojo: ya tuvo una lesión en {{parte}} ({{lado}}) el {{fecha}}. Puede contar como recurrencia o recidiva.",
    error: {
      jugador: "Elegí un jugador.",
      fecha: "Cargá la fecha de inicio de la lesión.",
      fechaFutura: "La fecha de inicio no puede ser futura.",
      fechaAntes: "Las fechas de transición, retorno y alta no pueden ser anteriores al inicio.",
      fechaFuturaOtra: "Ninguna fecha puede ser futura.",
      parte: "Elegí la parte del cuerpo lesionada.",
      lado: "Elegí el lado.",
      tipo: "Elegí el tipo de lesión.",
      imagen: "La hora de la imagen no es válida.",
      imagenAntes: "La imagen no puede ser de antes del día de la lesión.",
      lesionDespuesDeImagen: "La lesión no puede empezar después de la imagen ({{imagen}}).",
      solapada: "Ya hay una lesión activa en {{parte}} ({{lado}}) para este jugador.",
      noGuardar: "No se pudo guardar la lesión.",
      noBorrar: "No se pudo borrar la lesión.",
      noLeer: "No se pudieron leer las lesiones.",
      faltaMigracion: "La base todavía no tiene las tablas de lesiones: falta ejecutar la migración 20261002_lesiones_excel.sql en Supabase.",
      sinPermiso: "Tu cuenta no tiene permiso para cargar lesiones.",
    },
    reportes: {
      titulo: "Reportes",
      texto: "Lo que muestran las lesiones cargadas, de un jugador o del plantel.",
      ver: "Ver reportes",
      individual: "Reporte individual",
      individualTexto: "Un jugador: lesiones y días perdidos cada 1000 horas contra la referencia del plantel, dónde se lesionó y su historial",
      grupal: "Reporte grupal",
      grupalTexto: "El plantel: cada 1000 horas, meses, zonas, tipos y quiénes perdieron más días",
      crear: "Crear reportes",
      crearTexto: "Lo próximo: armar tus propios reportes con bloques (un gráfico, una tabla o un número), eligiendo qué medir, cómo separarlo y con qué filtros, y guardarlos para el club.",
      individualTitulo: "Reporte individual de lesiones",
      grupalTitulo: "REPORTE GRUPAL DE LESIONES",
      volver: "Reportes",
      imprimir: "Imprimir o guardar en PDF",
      elegirJugador: "¿De qué jugador?",
      cambiarJugador: "Cambiar jugador",
      periodo: "Período",
      periodos: {
        anio: "Este año",
        doce: "Últimos 12 meses",
        todo: "Todo",
        medida: "Elegir fechas",
      },
      desde: "Desde",
      hasta: "Hasta",
      cuales: "Qué lesiones",
      sinLeves: "Sin leves",
      soloMusculares: "Solo LM",
      todas: "Todas las lesiones",
      nacimiento: "Nacimiento",
      pie: "Pie dominante",
      kpiLesiones: "Lesiones",
      kpiDias: "Días perdidos",
      kpiActivas: "Abiertas hoy",
      kpiJugadores: "Jugadores lesionados",
      kpiPromedio: "Días por lesión (con alta)",
      kpiRecurrentes: "Recurrentes",
      cadaMil: "Cada 1000 horas",
      lesionesMil: "Lesiones c/ 1000 h",
      diasMil: "Días perdidos c/ 1000 h",
      tiposTodos: "Todos los tipos",
      tiposLM: "Solo LM",
      severidadTodas: "Todas",
      severidadSinLeves: "Sin leves",
      queEsLM: "LM = lesión muscular",
      indicadores: "Indicadores de lesión",
      tasas: "Tasas por 1000 horas",
      variantes: {
        todas: "Todas",
        sinLeves: "Sin leves",
        musculares: "Musculares (LM)",
        muscularesSinLeves: "LM sin leves",
      },
      referencia: "Referencia",
      comparado: {
        peor: "{{valor}} superior",
        mejor: "{{valor}} inferior",
        igual: "{{valor}} igual",
      },
      superiorRef: "Superior a la referencia",
      inferiorRef: "Inferior a la referencia",
      queEsRef: "Referencia = el valor del plantel (VR)",
      dondeSeLesiono: "Dónde se lesionó",
      calorEscala: "Lesiones por zona",
      masVeces: "Las zonas con más lesiones",
      zonasMas_one: "y {{n}} zona más",
      zonasMas_other: "y {{n}} zonas más",
      historialLesiones: "Historial de lesiones",
      registros_one: "{{n}} registro",
      registros_other: "{{n}} registros",
      cuentan: "Cuentan las lesiones con {{criterio}}.",
      faltaGps: "Faltan los minutos del GPS: sin ellos no se pueden sacar las cuentas cada 1000 horas.",
      sinLesionesJugador: "No tiene lesiones cargadas.",
      sinLesiones: "No hay lesiones en este período con estos filtros.",
      dondeSeLesionan: "Dónde se lesionan",
      abierta: "Sin alta",
      porMes: "Lesiones por mes",
      masDias: "Quiénes perdieron más días",
    },
    historial: {
      titulo: "Historial",
      texto: "Elegí un jugador y mirá todas sus lesiones, como en la base.",
      buscar: "Buscar un jugador...",
      sinLesiones: "Este jugador no tiene lesiones cargadas.",
      cantidad_one: "{{n}} lesión",
      cantidad_other: "{{n}} lesiones",
    },
    cuerpo: {
      figura: "Figura del cuerpo",
      donde: "Dónde fue la lesión",
      cuerpo: "Cuerpo",
      vista: "Cómo mirar la figura",
      frente: "De frente",
      espalda: "De espaldas",
      derecha: "DERECHA",
      izquierda: "IZQUIERDA",
      tocaZona: "Tocá la zona de la lesión.",
      regiones: {
        cabeza: "Cabeza y cuello",
        tronco: "Tronco",
        brazo_derecho: "Brazo derecho",
        brazo_izquierdo: "Brazo izquierdo",
        pierna_derecha: "Pierna derecha",
        pierna_izquierda: "Pierna izquierda",
      },
      queLado: "¿De qué lado?",
      elegido: "{{parte}} · {{lado}}",
      ubicacion: "Ubicación",
      estructuraTexto: "Tocá lo que corresponda: están las opciones de las listas que van en esta parte del cuerpo.",
      estructuraFigura: "Tocá en la figura el músculo, el tendón o el ligamento, o elegilo abajo. Lo oscuro no está en las listas de esta parte.",
      capa: "Qué músculos mirar",
      capas: {
        superficie: "Superficiales",
        profunda: "Profundos",
      },
      esquemas: {
        rodilla: "Rodilla por dentro",
        tobilloAfuera: "Tobillo por fuera",
        tobilloAdentro: "Tobillo por dentro",
        planta: "Planta del pie",
      },
      rotulos: {
        lca: "LCA",
        lcp: "LCP",
        lle: "LLE",
        lli: "LLI",
        ml: "ML",
        mm: "MM",
        anterior: "Anterior",
        medio: "Medio",
        posterior: "Posterior",
        sindesmosis: "Sindesmosis",
        deltoideo: "Deltoideo",
        musculos: "Músculos",
        aductor: "Aductor",
        fascia: "Fascia",
        insercion: "Inserción",
      },
      leyenda: {
        musculos: "Músculos",
        tendones: "Tendones",
        ligamentos: "Ligamentos",
      },
      sinEstructuras: "En las listas no hay músculos ni ligamentos para esta parte del cuerpo.",
      tercios: {
        proximal: "Proximal",
        medio: "Medio",
        distal: "Distal",
      },
      deLaLista: "Elegir de la lista",
      conFigura: "Elegir con la figura",
    },
    ficha: {
      resumen: "Resumen de la lesión",
      secciones: "Qué mirar",
      diasDeBaja: "Días de baja",
      cambios: "Cambios",
      ultimos: "Últimos cambios",
      ultimosTexto: "Los 5 más recientes",
      sinCambios: "Sin cambios registrados.",
      cambio: "{{fecha}} · {{quien}}",
      creada: "Carga",
      editada: "Edición",
      columnas: "Cambió: {{columnas}}",
    },
    ajustes: {
      titulo: "Ajustes",
      texto: "Lo que la app usa en Lesiones.",
      cabeceras: "Cabeceras",
      cabecerasTexto: "Cómo se llama cada columna del Excel",
      cabecerasAyuda: "Tocá un grupo o una columna para cambiarle el nombre en cada idioma. Las columnas también se pueden esconder del formulario.",
      listas: "Listas",
      listasTexto: "Las opciones de cada desplegable",
      listasAyuda: "Tocá una lista para agregar, renombrar o esconder opciones. Lo que ya está cargado no se pierde.",
      volver: "Volver a Ajustes",
      volverListas: "Volver a Listas",
      editarCabecera: "Cabecera",
      editarGrupo: "Grupo",
      grupoDe_one: "Grupo de {{n}} columna",
      grupoDe_other: "Grupo de {{n}} columnas",
      grupoAyuda: "Es la fila de arriba de las cabeceras: ordena la base, la carga por pasos y la ficha.",
      editarOpcion: "Opción",
      nuevaOpcion: "Agregar una opción",
      nombre: "Nombre en este idioma",
      nombreAyuda: "Para cambiarlo en otro idioma, cambiá el idioma de la app y volvé acá.",
      mostrar: "Se muestra",
      oculto: "Oculta",
      guardado: "Guardado",
      errorGuardar: "No se pudo guardar el cambio.",
      opciones_one: "{{n}} opción",
      opciones_other: "{{n}} opciones",
      porDefecto: "Del Excel: {{texto}}",
      faltaTexto: "Escribí el nombre.",
      noSeOculta: "Esta columna hace falta para registrar la lesión: siempre se muestra.",
      seUbicanSolas: "Las que agregues se ubican solas en el cuerpo, por su nombre.",
      vaEn: "En el cuerpo: {{partes}}",
      vaEnTodas: "No se reconoce en qué parte del cuerpo va: aparece en todas",
      vaConTercio: "Tercio: {{tercio}}",
      sinTercio: "Del músculo entero, sin tercio",
    },
    estado: {
      cargando: "Leyendo las lesiones…",
      sinConexion: "Sin conexión. Lesiones necesita señal para leer y guardar.",
    },
  },
};
