// Textos do app em português do Brasil. Mesmas chaves que es-AR.js: a prova
// automática falha se faltar alguma. Termos médicos: validar com o
// departamento médico do clube antes de usar nos relatórios.
export default {
  comun: {
    cancelar: "Cancelar",
    volver: "Voltar",
    guardar: "Salvar",
    guardando: "Salvando…",
    cerrar: "Fechar",
    listo: "Pronto",
    si: "Sim",
    no: "Não",
    hoy: "Hoje",
    actualizar: "Atualizar",
    actualizando: "Atualizando…",
    reintentar: "Tentar de novo",
    cargando: "Carregando…",
    salir: "Sair",
    saliendo: "Saindo…",
    sinConexion: "Sem conexão. Verifique o sinal e tente de novo.",
    idioma: "Idioma",
    todos: "Todos",
    sinDato: "Sem dado",
    elegir: "Escolha…",
    borrar: "Excluir",
    filtros: "Filtros",
    quitarFiltros: "Limpar filtros",
    cambiar: "Trocar",
  },
  nav: {
    partido: "Jogo",
    formacion: "Escalação",
    registros: "Registros",
    ajustes: "Ajustes",
    inicio: "Início",
    tareas: "Tarefas",
    lesionados: "Lesionados",
    historial: "Histórico",
    plantel: "Elenco",
  },
  acceso: {
    marca: "Registro Partido",
    volverPortal: "Voltar ao portal",
    cargandoTitulo: "Um momento…",
    cargandoTexto: "Estamos verificando sua conta.",
    cargandoTarda: "Está demorando mais que o normal. Sem sinal, pode levar até meio minuto.",
    recuperarTitulo: "Escolha uma senha nova",
    recuperarTexto: "A partir de agora você vai entrar com esta senha.",
    nuevaContrasena: "Nova senha",
    repetirContrasena: "Repetir senha",
    guardarContrasena: "Salvar senha",
    pendienteTitulo: "Sua conta está aguardando autorização",
    pendienteTexto: "A conta {{correo}} já foi criada. Quando o administrador autorizar, você vai poder entrar; se ele já avisou, toque em Verificar de novo.",
    bloqueadoTitulo: "Sua conta não tem acesso",
    bloqueadoTexto: "O administrador removeu o acesso desta conta. Se achar que é um erro, fale com ele.",
    sinModulosTitulo: "Sua conta não tem módulos habilitados",
    sinModulosTexto: "O administrador ainda não habilitou nenhum módulo para você. Quando habilitar, toque em Verificar de novo.",
    comprobar: "Verificar de novo",
    comprobando: "Verificando…",
    noPudimosTitulo: "Não conseguimos verificar sua conta",
    noPudimosTexto: "Tente de novo em instantes.",
    entrarTitulo: "Entre com sua conta",
    entrarTexto: "Use o e-mail e a senha com os quais você se cadastrou.",
    correo: "E-mail",
    contrasena: "Senha",
    correoEjemplo: "nome@clube.com",
    entrar: "Entrar",
    entrando: "Entrando…",
    olvide: "Esqueci minha senha",
    enviando: "Enviando…",
    crear: "Criar uma conta",
    creando: "Criando…",
    notaAutorizacion: "Contas novas precisam da autorização do administrador antes de entrar.",
    error: {
      credenciales: "O e-mail ou a senha não estão corretos.",
      noConfirmado: "Você ainda não confirmou seu e-mail. Procure a mensagem na sua caixa de entrada (e no spam).",
      yaRegistrado: "Esse e-mail já tem uma conta. Entre com sua senha ou peça uma nova.",
      demasiados: "Houve tentativas demais seguidas. Espere alguns minutos e tente de novo.",
      mismaContrasena: "A senha nova tem que ser diferente da anterior.",
      debil: "A senha é fácil demais de adivinhar. Use pelo menos 8 caracteres, misturando letras e números.",
      reautenticar: "Por segurança, peça um link novo em Esqueci minha senha e tente de novo.",
      enlaceVencido: "O link do e-mail venceu ou já foi usado. Peça um novo.",
      enlaceInvalido: "O link do e-mail não é válido. Peça um novo.",
      enlaceRecuperacion: "O link de recuperação não é válido ou já venceu. Peça um novo em Esqueci minha senha.",
      enlaceNoValido: "O link de recuperação não é válido. Peça um novo.",
      minimo8: "A senha nova precisa ter pelo menos 8 caracteres.",
      noCoinciden: "As senhas não são iguais.",
      sesionNoAbierta: "Não foi possível abrir a sessão depois de trocar a senha.",
      sinConexionCuenta: "Sem conexão, não conseguimos verificar sua conta. Tente de novo quando tiver sinal.",
      noComprobar: "Não foi possível verificar sua conta. Tente de novo.",
      noEntrar: "Não foi possível entrar. Tente de novo.",
      completar: "Preencha o e-mail e a senha.",
      noCrear: "Não foi possível criar a conta.",
      escribiCorreo: "Primeiro escreva seu e-mail, assim enviamos o link.",
      noEnviarCorreo: "Não foi possível enviar o e-mail de recuperação.",
      noCambiarContrasena: "Não foi possível trocar a senha.",
    },
    cuentaCreada: "Conta criada. Enviamos um e-mail para confirmá-la: abra o link e entre de novo. Depois o administrador precisa autorizá-la.",
    enlaceEnviado: "Se esse e-mail tiver uma conta, você vai receber um link para escolher uma senha nova. Confira também a pasta de spam.",
  },
  portal: {
    pregunta: "O que você vai fazer hoje?",
    elegi: "Escolha por onde começar.",
    unSolo: "Por enquanto você tem este módulo habilitado.",
    cuentas: "Contas",
    modulos: "Módulos",
    salir: "Sair",
    entrar: "Entrar",
    entrarA: "Entrar em {{modulo}}",
    entrando: "Entrando…",
    enPrueba: "Em teste",
    nuevo: "Novo",
    partidoTitulo: "Jogo",
    partidoTexto: "Registre o jogo ao vivo: escalação, tempos e substituições.",
    flujoTitulo: "Rotina diária",
    flujoTexto: "Tudo do dia depois do treino: cortes, dados, planilha e PSE.",
    lesionesTitulo: "Lesões",
    lesionesTexto: "Quem está lesionado, desde quando e quando volta. Registro em quatro toques.",
  },
  club: {
    titulo: "Com qual clube você trabalha?",
    texto: "Escolha o clube. Depois dá para trocar no portal.",
    cargando: "Buscando os clubes…",
    vacio: "Ainda não há clubes cadastrados. Crie o primeiro.",
    error: "Não foi possível ler os clubes.",
    crear: "Criar um clube",
    nombre: "Nome do clube",
    crearBoton: "Criar e escolher",
    creando: "Criando…",
    cambiar: "Trocar de clube",
    elegido: "Clube",
  },
  openfield: {
    abriendoTitulo: "Um momento…",
    abriendoTexto: "Estamos conectando com o OpenField.",
    sinAccesoTitulo: "Sem acesso à Rotina diária",
    errorTitulo: "Não conseguimos conectar com o OpenField",
    errorTexto: "Não foi possível abrir a sessão do OpenField. Tente de novo.",
    iniciaSesion: "Entre na sua conta para acessar o OpenField.",
  },
  cuentas: {
    kicker: "Administração",
    titulo: "Contas",
    texto: "Aqui você decide quem pode entrar no app e quais módulos cada um usa. As mudanças valem na hora.",
    porAutorizar: "Aguardando autorização",
    conAcceso: "Com acesso",
    sinAcceso: "Sem acesso",
    vacioPendientes: "Não há contas aguardando autorização.",
    vacioConAcceso: "Ainda não há contas com acesso.",
    vacioSinAcceso: "Não há contas sem acesso.",
    tuCuenta: "Sua conta",
    administrador: "Administrador",
    correoSinConfirmar: "E-mail não confirmado",
    creadaEl: "Criada em {{fecha}}",
    ultimoCambio: "· Última alteração em {{fecha}}",
    autorizar: "Autorizar",
    rechazar: "Recusar",
    quitarAcceso: "Remover acesso",
    quePuedeUsar: "O que {{correo}} pode usar",
    modulos: {
      partido: "Jogo",
      flujo: "Rotina diária",
      lesiones: "Lesões",
      admin: "Administrador",
    },
    errorLeer: "Não foi possível ler as contas.",
    errorCambiar: "Não foi possível alterar a conta.",
    marcaModulo: "Marque pelo menos um módulo antes de autorizar.",
    rechazarTitulo: "Recusar esta conta?",
    quitarTitulo: "Remover o acesso?",
    rechazarTexto: "{{correo}} não vai poder entrar no app. Se mudar de ideia, você pode autorizá-la em Sem acesso.",
    quitarTexto: "{{correo}} deixa de ter acesso ao app na hora. Você pode autorizá-la de novo quando quiser.",
    siRechazar: "Sim, recusar",
    siQuitar: "Sim, remover",
    laCuenta: "A conta",
    sinCorreo: "(sem e-mail)",
  },
  lesiones: {
    titulo: "Lesões",
    hoy: "Lesionados hoje",
    activas_one: "{{n}} lesão ativa",
    activas_other: "{{n}} lesões ativas",
    sinActivas: "Não há lesões ativas. Todo o elenco está disponível.",
    nueva: "Nova lesão",
    darAlta: "Alta médica",
    borrar: "Excluir lesão",
    borrarTitulo: "Excluir esta lesão?",
    borrarTexto: "A lesão de {{jugador}} será excluída. Fica anotado no histórico de alterações.",
    siBorrar: "Sim, excluir",
    borrada: "Lesão excluída",
    editar: "Editar",
    verDetalle: "Ver detalhes",
    caso: "Caso {{n}}",
    dias_one: "{{n}} dia",
    dias_other: "{{n}} dias",
    horas_one: "{{n}} hora",
    horas_other: "{{n}} horas",
    anios_one: "{{n}} ano",
    anios_other: "{{n}} anos",
    desde: "desde {{fecha}}",
    altaEl: "alta em {{fecha}}",
    etapa: {
      lesionado: "Lesionado",
      transicion: "Em transição",
      entrenando: "Treinando",
      alta: "Com alta",
    },
    altaTitulo: "Dar a alta médica?",
    altaTexto: "{{jugador}} volta a competir a partir da data que você escolher.",
    altaFecha: "Retorno à competição",
    siAlta: "Sim, dar alta",
    formNueva: "Nova lesão",
    formEditar: "Editar lesão",
    jugador: "Jogador",
    sinJugadores: "Não há jogadores cadastrados. Eles são adicionados em Jogo › Ajustes › Jogadores.",
    grupos: {
      registro: "Registro",
      jugador: "Jogador",
      lesion: "Lesão",
      imagen: "Imagens",
      fechas: "Datas e recuperação",
      notas: "Notas",
    },
    calculado: "Calculado automaticamente",
    delJugador: "Vem da ficha do jogador",
    sinDato: "—",
    guardado: "Lesão salva",
    altaGuardada: "Alta salva",
    avisoRecidiva: "Possível recidiva: já teve uma lesão em {{parte}} ({{lado}}) em {{fecha}}.",
    error: {
      jugador: "Escolha um jogador.",
      fecha: "Informe a data de início da lesão.",
      fechaFutura: "A data de início não pode ser no futuro.",
      fechaAntes: "As datas de transição, retorno e alta não podem ser anteriores ao início.",
      fechaFuturaOtra: "Nenhuma data pode ser no futuro.",
      parte: "Escolha a parte do corpo lesionada.",
      lado: "Escolha o lado.",
      solapada: "Já existe uma lesão ativa em {{parte}} ({{lado}}) para este jogador.",
      noGuardar: "Não foi possível salvar a lesão.",
      noBorrar: "Não foi possível excluir a lesão.",
      noLeer: "Não foi possível ler as lesões.",
      faltaMigracion: "O banco ainda não tem as tabelas de lesões: falta executar a migração 20261002_lesiones_excel.sql no Supabase.",
      sinPermiso: "Sua conta não tem permissão para registrar lesões.",
    },
    plantel: {
      titulo: "Elenco",
      texto: "Quem está disponível hoje.",
      disponibles: "{{n}} de {{total}} disponíveis",
      disponible: "Disponível",
      reintegrandose: "Em reintegração",
      lesionado: "Lesionado",
      sinPlantel: "Não há jogadores cadastrados neste time.",
      datos: "Dados do jogador",
      datosTexto: "O que o Excel pede de cada jogador. Preenche-se uma vez e fica.",
      guardados: "Dados salvos",
      errorGuardar: "Não foi possível salvar os dados do jogador.",
    },
    historial: {
      titulo: "Histórico",
      texto: "Todas as lesões registradas, da mais recente à mais antiga.",
      vacio: "Ainda não há lesões registradas.",
      buscar: "Buscar por jogador, diagnóstico...",
      sinResultados: "Nenhuma lesão entra nesse filtro.",
      cantidad_one: "{{n}} lesão",
      cantidad_other: "{{n}} lesões",
      cambios: "Histórico de alterações",
      sinCambios: "Sem alterações registradas.",
      cambio: "{{fecha}} · {{quien}}",
      creada: "Registro",
      editada: "Edição",
    },
    filtro: {
      filtrarPor: "Filtrar por",
      filtrar: "Filtrar as lesões",
      borrar: "Limpar os filtros",
      cambiar: "Trocar",
      conCuales: "Com quais",
      multi: "Multi-Filtro",
      todos: "Todas",
      jugador: "Jogador",
      buscarJugador: "Buscar um jogador...",
      ningunJugador: "Nenhum jogador com esse nome.",
      etapa: "Etapa",
      fecha: "Data de início",
      desde: "De",
      hasta: "Até",
    },
    ajustes: {
      titulo: "Ajustes",
      texto: "O que o app usa em Lesões.",
      cabeceras: "Cabeçalhos",
      cabecerasTexto: "Como se chama cada coluna do Excel",
      cabecerasAyuda: "Toque em uma coluna para mudar o nome em cada idioma ou escondê-la do formulário.",
      listas: "Listas",
      listasTexto: "As opções de cada lista suspensa",
      listasAyuda: "Toque em uma lista para adicionar, renomear ou esconder opções. O que já foi registrado não se perde.",
      volver: "Voltar aos Ajustes",
      volverListas: "Voltar às Listas",
      editarCabecera: "Cabeçalho",
      editarOpcion: "Opção",
      nuevaOpcion: "Adicionar uma opção",
      enEspanol: "Em espanhol",
      enPortugues: "Em português",
      mostrar: "Aparece",
      oculto: "Oculta",
      guardado: "Salvo",
      errorGuardar: "Não foi possível salvar a alteração.",
      opciones_one: "{{n}} opção",
      opciones_other: "{{n}} opções",
      porDefecto: "Do Excel: {{texto}}",
      faltaTexto: "Escreva o nome em pelo menos um idioma.",
    },
    estado: {
      cargando: "Lendo as lesões…",
      sinConexion: "Sem conexão. Lesões precisa de sinal para ler e salvar.",
    },
  },
};
