// Textos do app em português do Brasil. Mesmas chaves que es-AR.js: a prova
// automática falha se faltar alguma. Termos médicos: validar com o
// departamento médico do clube antes de usar nos relatórios.
export default {
  comun: {
    cancelar: "Cancelar",
    volver: "Voltar",
    guardar: "Salvar",
    guardando: "Salvando…",
    cerrar: "Fechar",
    listo: "Pronto",
    si: "Sim",
    no: "Não",
    hoy: "Hoje",
    actualizar: "Atualizar",
    actualizando: "Atualizando…",
    reintentar: "Tentar de novo",
    cargando: "Carregando…",
    salir: "Sair",
    saliendo: "Saindo…",
    sinConexion: "Sem conexão. Verifique o sinal e tente de novo.",
    idioma: "Idioma",
    todos: "Todos",
    sinDato: "Sem dado",
    buscar: "Escreva para buscar...",
    sinCoincidencias: "Nenhum resultado.",
    elegir: "Escolha…",
    borrar: "Excluir",
    filtros: "Filtros",
    quitarFiltros: "Limpar filtros",
    cambiar: "Trocar",
  },
  nav: {
    partido: "Jogo",
    formacion: "Escalação",
    registros: "Registros",
    ajustes: "Ajustes",
    inicio: "Início",
    tareas: "Tarefas",
    lesionados: "Novos casos",
    historial: "Histórico individual",
    base: "Base",
    jugadores: "Jogadores",
    reportes: "Relatórios",
    posiciones: "Posições",
    catapult: "Catapult",
    referencias: "Valores de referência",
  },
  acceso: {
    marca: "Registro Partido",
    volverPortal: "Voltar ao portal",
    cargandoTitulo: "Um momento…",
    cargandoTexto: "Estamos verificando sua conta.",
    cargandoTarda: "Está demorando mais que o normal. Sem sinal, pode levar até meio minuto.",
    cargandoTardaConCopia: "Está demorando mais que o normal. Se o sinal não ajudar, você pode entrar com a conta salva neste celular.",
    entrarSinConexion: "Entrar sem conexão",
    recuperarTitulo: "Escolha uma senha nova",
    recuperarTexto: "A partir de agora você vai entrar com esta senha.",
    nuevaContrasena: "Nova senha",
    repetirContrasena: "Repetir senha",
    guardarContrasena: "Salvar senha",
    pendienteTitulo: "Sua conta está aguardando autorização",
    pendienteTexto: "Sua conta {{correo}} já foi criada. Quando liberarem seu acesso, toque em Verificar de novo.",
    bloqueadoTitulo: "Sua conta não tem acesso",
    bloqueadoTexto: "Esta conta não pode entrar no app. Se achar que é um erro, avise seu clube.",
    comprobar: "Verificar de novo",
    comprobando: "Verificando…",
    noPudimosTitulo: "Não conseguimos verificar sua conta",
    noPudimosTexto: "Tente de novo em instantes.",
    entrarTitulo: "Entre com sua conta",
    entrarTexto: "Use o e-mail e a senha com os quais você se cadastrou.",
    correo: "E-mail",
    contrasena: "Senha",
    correoEjemplo: "nome@clube.com",
    entrar: "Entrar",
    entrando: "Entrando…",
    olvide: "Esqueci minha senha",
    enviando: "Enviando…",
    crear: "Criar uma conta",
    creando: "Criando…",
    notaAutorizacion: "Se você foi convidado para um clube, crie a conta com esse mesmo e-mail. Se não, ao entrar você pede acesso ao seu clube.",
    error: {
      credenciales: "O e-mail ou a senha não estão corretos.",
      noConfirmado: "Você ainda não confirmou seu e-mail. Procure a mensagem na sua caixa de entrada (e no spam).",
      yaRegistrado: "Esse e-mail já tem uma conta. Entre com sua senha ou peça uma nova.",
      demasiados: "Houve tentativas demais seguidas. Espere alguns minutos e tente de novo.",
      mismaContrasena: "A senha nova tem que ser diferente da anterior.",
      debil: "A senha é fácil demais de adivinhar. Use pelo menos 8 caracteres, misturando letras e números.",
      reautenticar: "Por segurança, peça um link novo em Esqueci minha senha e tente de novo.",
      enlaceVencido: "O link do e-mail venceu ou já foi usado. Peça um novo.",
      enlaceInvalido: "O link do e-mail não é válido. Peça um novo.",
      enlaceRecuperacion: "O link de recuperação não é válido ou já venceu. Peça um novo em Esqueci minha senha.",
      enlaceNoValido: "O link de recuperação não é válido. Peça um novo.",
      minimo8: "A senha nova precisa ter pelo menos 8 caracteres.",
      noCoinciden: "As senhas não são iguais.",
      sesionNoAbierta: "Não foi possível abrir a sessão depois de trocar a senha.",
      sinConexionCuenta: "Sem conexão, não conseguimos verificar sua conta. Tente de novo quando tiver sinal.",
      noComprobar: "Não foi possível verificar sua conta. Tente de novo.",
      noEntrar: "Não foi possível entrar. Tente de novo.",
      completar: "Preencha o e-mail e a senha.",
      noCrear: "Não foi possível criar a conta.",
      escribiCorreo: "Primeiro escreva seu e-mail, assim enviamos o link.",
      noEnviarCorreo: "Não foi possível enviar o e-mail de recuperação.",
      noCambiarContrasena: "Não foi possível trocar a senha.",
    },
    cuentaCreada: "Conta criada. Enviamos um e-mail para confirmá-la: abra o link e entre de novo.",
    enlaceEnviado: "Se esse e-mail tiver uma conta, você vai receber um link para escolher uma senha nova. Confira também a pasta de spam.",
  },
  portal: {
    pregunta: "O que você vai fazer hoje?",
    elegi: "Escolha por onde começar.",
    unSolo: "Por enquanto você tem este módulo habilitado.",
    cuentas: "Contas",
    clubesApp: "Clubes do app",
    modulos: "Módulos",
    salir: "Sair",
    entrar: "Entrar",
    entrarA: "Entrar em {{modulo}}",
    entrando: "Entrando…",
    enPrueba: "Em teste",
    nuevo: "Novo",
    partidoTitulo: "Jogo",
    partidoTexto: "Registre o jogo ao vivo: escalação, tempos e substituições.",
    flujoTitulo: "Rotina diária",
    flujoTexto: "Tudo do dia depois do treino: cortes, dados, planilha e PSE.",
    basesTitulo: "Bases de Dados",
    basesTexto: "Cada base do clube num só lugar, para registrar, consultar e tirar relatórios.",
    datosTitulo: "Dados básicos",
    datosTexto: "Os jogadores e seus dados, numa tabela que copia e cola como no Excel.",
    notasTitulo: "Notas",
    notasTexto: "As melhorias que você quer fazer no app, anotadas para o seu clube ver.",
  },
  // Bases de Dados: um cartão por base, como na tela principal.
  notas: {
    kicker: "Notas do clube",
    titulo: "Notas",
    texto: "As melhorias que você quer fazer no app. Quem vê é o pessoal de {{club}}; nenhum outro clube.",
    nuevaTitulo: "Nova nota",
    placeholder: "Escreva a melhoria…",
    agregar: "Adicionar nota",
    pendientesTitulo: "A fazer",
    hechasTitulo: "Feitas",
    vacioPendientes: "Não há nada a fazer.",
    marcarHecha: "Marcar como feita",
    volverAPendientes: "Voltar para a fazer",
    editar: "Corrigir",
    editarTitulo: "Corrigir a nota",
    guardar: "Salvar",
    borrar: "Apagar",
    borrarTitulo: "Apagar esta nota?",
    borrarTexto: "Não dá para desfazer.",
    siBorrar: "Sim, apagar",
    errorCargar: "Não foi possível ler as notas. Tente de novo.",
    errorGuardar: "Não foi possível salvar a nota. Tente de novo.",
    errorBorrar: "Não foi possível apagar a nota. Tente de novo.",
    errorTexto: "Escreva algo na nota.",
    errorSoloAutor: "Só quem escreveu esta nota pode corrigi-la.",
    errorSinPermiso: "Você não tem permissão para isso neste clube.",
    errorFaltaMigracion: "Falta atualizar a base: rode o SQL de Notas (20261013b_notas.sql) no Supabase.",
  },
  bases: {
    elegi: "Escolha qual base abrir.",
    ninguna: "Sua conta não tem nenhuma base habilitada neste clube.",
    lesionesTitulo: "Lesões",
    lesionesTexto: "Quem está lesionado, desde quando e quando volta, com a base e os relatórios.",
    evaluacionesTitulo: "Avaliações",
    evaluacionesTexto: "Os testes físicos de cada jogador, com o relatório, os valores de referência e as mesmas cores do Excel.",
  },
  evaluaciones: {
    titulo: "Avaliações",
    texto: "Como no Excel: o relatório de cima e as cores se recalculam com as linhas que o filtro deixa ver.",
    agregar: "Adicionar avaliação",
    agregarTitulo: "De quem é a avaliação?",
    agregada: "Avaliação adicionada: complete-a na tabela.",
    borrarTitulo: "Apagar esta avaliação?",
    borrarTexto: "A de {{jugador}} de {{fecha}}. Não dá para desfazer.",
    sinFecha: "sem data",
    siBorrar: "Sim, apagar",
    borrada: "Avaliação apagada.",
    comparar: "Comparar com",
    sinReferencias: "Ainda não estão os valores de referência deste teste: as classes ficam vazias até serem carregados.",
    totalEvaluaciones: "Quantas avaliações aparecem",
    estado: {
      cargando: "Lendo as avaliações…",
      sinConexion: "Sem conexão. Avaliações precisa de sinal para ler e salvar.",
    },
    referencias: {
      titulo: "Valores de referência",
      texto: "Os do Excel, por categoria: com eles se calcula cada classe e a comparação do relatório.",
      resumen: "RESUMO CATEGORIAS (Médias)",
      categoria: "Categoria",
      pro: "Pro",
      sinDatos: "Ainda não estão os valores de referência deste teste. São carregados uma vez só, com os valores exatos do Excel.",
    },
    importar: {
      boton: "Colar do Excel",
      titulo: "Colar avaliações do Excel",
      texto: "No Excel, na planilha do teste, tire os filtros e copie a tabela desde a linha de títulos (a que diz nº Eva, Fecha, Jugador…) até a última avaliação, e cole aqui. Antes de carregar dá para ver o que acontece com cada linha. O que o Excel calcula não se cola: a app calcula.",
      pegarAca: "Cole aqui o que você copiou do Excel",
      borrar: "Apagar o colado",
      sinCabeceras: "Não encontrei a linha de títulos. Copie a tabela junto com a linha que diz Jugador.",
      sinFilas: "Abaixo dos títulos não há avaliações.",
      anio: "As datas vêm sem ano: de que ano são?",
      anioAyuda: "Se forem de anos diferentes, no Excel coloque a coluna Fecha no formato dd/mm/aaaa e copie de novo.",
      filas_one: "{{n}} linha no colado",
      filas_other: "{{n}} linhas no colado",
      nuevas_one: "{{n}} para carregar",
      nuevas_other: "{{n}} para carregar",
      yaEstan_one: "{{n}} já está na app",
      yaEstan_other: "{{n}} já estão na app",
      conProblemas_one: "{{n}} com problemas",
      conProblemas_other: "{{n}} com problemas",
      porElegir_one: "{{n}} para escolher",
      porElegir_other: "{{n}} para escolher",
      noVan_one: "{{n}} não é carregada",
      noVan_other: "{{n}} não são carregadas",
      fueraDeDatos_one: "{{n}} nome não está em Dados básicos: toque nele para escolher o que fazer, ou salve assim mesmo.",
      fueraDeDatos_other: "{{n}} nomes não estão em Dados básicos: toque em cada um para escolher o que fazer, ou salve assim mesmo.",
      guardarTodasIgual_one: "Salvar assim mesmo a que não está em Dados básicos",
      guardarTodasIgual_other: "Salvar assim mesmo as {{n}} que não estão em Dados básicos",
      quienEs: "O que fazemos com {{nombre}}?",
      comoPersona: "Salvar com este nome (não entra em Dados básicos)",
      noCargar: "Não carregar",
      es: "É {{jugador}}",
      seGuardaComoPersona: "Não está em Dados básicos: a avaliação é salva com este nome e o nome não entra em Dados básicos.",
      seGuardaComo: "Não está em Dados básicos: a avaliação é salva como {{nombre}}, escrito como em outra avaliação da mesma pessoa, e o nome não entra em Dados básicos.",
      estado: {
        nueva: "É carregada",
        yaEsta: "Já está na app",
        sinJugador: "Não está em Dados básicos",
        dudoso: "Quem é?",
        comoPersona: "Salva com este nome",
        noVa: "Não é carregada",
        conProblemas: "Não é carregada",
      },
      sinJugador: "Este nome não está em Dados básicos. Escolha se é salvo com este nome (não entra em Dados básicos), se é um jogador da lista ou se não é carregado.",
      jugadorDudoso: "Em Dados básicos há mais de um jogador com um nome assim: escolha qual é, ou salve com este nome.",
      fechaMal: "A data não se entende: escreva como 12/06/2026.",
      fechaFutura: "A data é posterior a hoje.",
      repetida: "Esta avaliação está duas vezes no colado.",
      nombreLargo: "O nome é longo demais para salvar (até 120 letras).",
      sinNombre: "Falta o nome: não se sabe de quem é.",
      sinNombreFila: "Sem nome",
      plantelSinLeer: "Não foi possível ler Dados básicos, e sem isso não se sabe quem é cada um. Volte e tente de novo.",
      quedanSinElegir_one: "{{n}} nome continua sem escolher: essa avaliação não é carregada até você escolher o que fazer.",
      quedanSinElegir_other: "{{n}} nomes continuam sem escolher: essas avaliações não são carregadas até você escolher o que fazer.",
      aviso: "«{{valor}}» não foi entendido em {{columna}}: fica vazio.",
      cargar_one: "Carregar {{n}} avaliação",
      cargar_other: "Carregar {{n}} avaliações",
      nadaQueCargar: "Nada para carregar",
      cargando: "Carregando {{n}} de {{total}}…",
      listo_one: "Pronto: {{n}} avaliação carregada.",
      listo_other: "Pronto: {{n}} avaliações carregadas.",
      fallaron_one: "{{n}} avaliação não pôde ser carregada:",
      fallaron_other: "{{n}} avaliações não puderam ser carregadas:",
      fallo: "{{fecha}} · {{nombre}}: {{error}}",
    },
    error: {
      noLeer: "Não foi possível ler as avaliações.",
      noGuardar: "Não foi possível salvar a avaliação.",
      noBorrar: "Não foi possível apagar a avaliação.",
      faltaMigracion: "A base ainda não tem Avaliações: falta rodar o SQL 20261012_evaluaciones.sql no Supabase.",
      jugadorDeOtroClub: "Esse jogador não é deste clube.",
      fechaFutura: "A data da avaliação não pode ser posterior a hoje.",
      sinJugador: "Uma avaliação tem que ser de alguém: escolha o jogador.",
      sinPermiso: "Sua conta não tem Avaliações neste clube.",
      sinConexion: "Sem conexão: não foi possível salvar.",
    },
  },
  tabla: {
    copiar: "Copiar",
    pegar: "Colar",
    ficha: "Ver ficha",
    borrarFila: "Excluir linha",
    sinSeleccion: "Toque em uma célula para começar. Segure um cabeçalho para movê-lo ou arraste a borda dele para mudar a largura.",
    filas_one: "{{n}} linha",
    filas_other: "{{n}} linhas",
    filasDe_one: "{{n}} de {{total}} linha",
    filasDe_other: "{{n}} de {{total}} linhas",
    ancho: "Arraste para mudar a largura (dois cliques: volta à largura padrão)",
    seleccion_one: "{{n}} célula selecionada",
    seleccion_other: "{{n}} células selecionadas",
    copiado_one: "{{n}} célula copiada",
    copiado_other: "{{n}} células copiadas",
    pegado_one: "{{n}} célula colada",
    pegado_other: "{{n}} células coladas",
    ignoradas_one: "{{n}} não foi entendida ou não pode mudar",
    ignoradas_other: "{{n}} não foram entendidas ou não podem mudar",
    horasMalEscritas: "As horas se escrevem como no Excel: 30:14:20, 30:14 ou 30,5.",
    tiempoMalEscrito: "Os tempos se escrevem em minutos e segundos: 3:04 ou 3,04 (ou 45, só segundos).",
    nadaQuePegar: "Não há nada para colar. Copie células do Excel ou desta tabela.",
    sinPermisoPegar: "O celular não deixa ler o que foi copiado. Cole com Ctrl+V dentro de uma célula.",
    editar: "Toque duas vezes em uma célula para mudá-la.",
    vacio: "Ainda não há linhas.",
    guardando: "Salvando…",
    filtrar: "Filtrar ou ordenar {{columna}}",
    filtroTitulo: "Filtrar: {{columna}}",
    buscarValor: "Buscar…",
    todos: "Todos",
    ninguno: "Nenhum",
    vacias: "(Vazias)",
    ordenarAsc: "Do menor ao maior",
    ordenarDesc: "Do maior ao menor",
    quitarFiltro: "Tirar filtro",
    aplicar: "Aplicar",
    quitarFiltros: "Tirar filtros",
    sinResultados: "Nenhuma linha passa nos filtros.",
    nadaEnLista: "Nenhum valor coincide.",
  },
  datos: {
    titulo: "Dados básicos",
    texto: "Os jogadores do clube com o que cada módulo precisa. Toque em uma célula para selecionar, duas vezes para mudar.",
    textoCorto: "Os jogadores do clube com o que cada módulo precisa.",
    agregar: "Adicionar jogador",
    nombre: "Nome e sobrenome",
    foto: "Foto (link)",
    horasPrevias: "Horas anteriores",
    actual: "Atual",
    yaNoEsta: "Já não está",
    leyendaYaNoEsta: "Nesta cor, os que já não estão no elenco atual (Dados básicos › Atual).",
    actuales_one: "{{n}} no elenco atual",
    actuales_other: "{{n}} no elenco atual",
    agregado: "Jogador adicionado",
    borrarTitulo: "Excluir o jogador?",
    borrarTexto: "Excluir é para um jogador cadastrado por engano: {{jugador}} sai da lista de todos os módulos. Se ele já não está no clube, melhor desmarcar Atual (os dados ficam). Com lesões ou avaliações registradas não dá para excluir.",
    siBorrar: "Sim, excluir",
    borrado: "Jogador excluído",
    guardado: "Salvo",
    jugadores_one: "{{n}} jogador",
    jugadores_other: "{{n}} jogadores",
    importar: {
      boton: "Colar do Excel",
      titulo: "Colar do Excel",
      texto: "No Excel, copie a tabela de Dados Básicos junto com a linha de cabeçalhos (Nome e Sobrenome, Categoria, D. Nac., P. Dominante, Posicao, Links das fotos) e cole aqui. Antes de carregar dá para ver o que acontece com cada jogador.",
      pegarAca: "Cole aqui o que você copiou do Excel",
      borrar: "Apagar o colado",
      sinCabeceras: "Não encontrei a linha de cabeçalhos. Copie a tabela junto com a linha que diz Nome e Sobrenome.",
      sinFilas: "Abaixo dos cabeçalhos não há jogadores.",
      jugadores_one: "{{n}} jogador no colado",
      jugadores_other: "{{n}} jogadores no colado",
      nuevos_one: "{{n}} novo",
      nuevos_other: "{{n}} novos",
      conCambios: "{{n}} com alterações",
      iguales: "{{n}} sem alterações",
      quienEs: "Quem é {{nombre}} no app?",
      nuevo: "Jogador novo",
      noCargar: "Não carregar",
      es: "É {{jugador}}",
      pareceSer: "É {{jugador}}?",
      repetido: "Repetido no colado",
      trae: "Traz: {{columnas}}",
      cambia: "Muda: {{columnas}}",
      sinCambios: "Já tem estes dados.",
      cambiaria: "Se for ele, muda: {{columnas}}",
      confirmar: "Sim, é {{jugador}}",
      porConfirmar_one: "{{n}} para confirmar",
      porConfirmar_other: "{{n}} para confirmar",
      sinDatos: "Só o nome.",
      aviso: "«{{valor}}» não foi entendido em {{columna}}: fica como está.",
      cargar_one: "Carregar {{n}} jogador",
      cargar_other: "Carregar {{n}} jogadores",
      nadaQueCargar: "Nada para carregar",
      cargando: "Carregando {{n}} de {{total}}…",
      listo: "Pronto: {{nuevos}} e {{actualizados}}.",
      actualizados_one: "{{n}} atualizado",
      actualizados_other: "{{n}} atualizados",
      fallaron_one: "{{n}} jogador não pôde ser carregado:",
      fallaron_other: "{{n}} jogadores não puderam ser carregados:",
      fallo: "{{nombre}}: {{error}}",
      sinDatosGuardados: "foi adicionado, mas os dados não foram salvos ({{error}})",
    },
    error: {
      nombre: "Escreva o nome.",
      repetido: "Esse jogador já está na lista. Se ele voltou ao clube, marque Atual.",
      guardar: "Não foi possível salvar.",
      leer: "Não foi possível ler os jogadores.",
      horas: "As horas se escrevem como no Excel: 30:14:20, 30:14 ou 30,5.",
      nacimientoFuturo: "A data de nascimento não pode ser posterior a hoje.",
      borrar: "Não foi possível excluir.",
      faltanHorasPrevias: "Para salvar as horas anteriores falta rodar no Supabase o SQL das horas anteriores.",
      borrarConDatos: "Tem lesões ou avaliações registradas e não pode ser excluído: se ele já não está no clube, desmarque Atual.",
      faltaActual: "Para marcar quem está no elenco atual falta rodar no Supabase o SQL 20261011_jugadores_actual.sql.",
    },
    vacio: "Ainda não há jogadores cadastrados.",
    posiciones: {
      titulo: "Onde cada um joga",
      texto: "As posições e as funções que Jogo usa para montar a escalação.",
      buscar: "Buscar jogador",
      nadie: "Nenhum jogador com esse nome.",
      agregarPuesto: "Adicionar posição",
      quitarPuesto: "Tirar esta posição",
    },
    puestos: {
      LAT: "Lateral",
      CAR: "Ala",
      DEF: "Zagueiro",
      VD: "Volante defensivo",
      VC: "Volante central",
      VM: "Volante misto",
      VOL: "Volante",
      VO: "Meia ofensivo",
      EXT: "Ponta",
      MP: "Meia-atacante",
      DEL: "Centroavante",
    },
    roles: {
      Defensa: "Defesa",
      Mediocampo: "Meio-campo",
      Ataque: "Ataque",
    },
    catapult: {
      titulo: "Coletes da Catapult",
      texto: "Cada jogador é vinculado uma vez ao seu colete para que os dados da Rotina diária cheguem à pessoa certa.",
      noLeer: "Não foi possível ler a lista de jogadores.",
      faltaMigracion: "A lista de jogadores ainda não tem o vínculo com a Catapult: falta executar a migração 20260920_jugadores_catapult.sql no Supabase.",
      yaVinculado: "Esse atleta da Catapult já está vinculado a outro jogador.",
      noChalecos: "Não foi possível ler os coletes.",
      conChaleco: "{{n}} com colete",
      chaleco: "Colete: {{chaleco}}",
      chalecoDe: "Colete de {{jugador}}",
      sinChaleco: "Sem colete",
      opcionSin: "— Sem colete —",
      repetido: "Repetido",
      yaNoExiste: "Esse colete não existe mais",
      guardado: "Salvo",
      exacto: "Coincide",
      probable: "Parecido, confira",
      aMano: "Escolhido à mão",
      emparejar: "Vincular com os coletes",
      emparejarTexto: "Busca os coletes das últimas sessões e propõe quem é quem. Depois você salva.",
      buscar: "Buscar coletes",
      buscando: "Buscando…",
      resumen: "Coletes encontrados: {{chalecos}} · coincidem: {{exactos}} · parecidos: {{probables}} · sem proposta: {{sinPropuesta}} · não existem mais: {{ausentes}}",
      hayRepetidos: "Há um colete escolhido para mais de um jogador. Corrija antes de salvar.",
      sinCambios: "Sem mudanças para salvar",
      guardar_one: "Salvar {{n}} mudança",
      guardar_other: "Salvar {{n}} mudanças",
      guardados_one: "{{n}} mudança salva.",
      guardados_other: "{{n}} mudanças salvas.",
    },
  },
  club: {
    titulo: "Com qual clube você trabalha?",
    texto: "Escolha o clube. Depois dá para trocar no portal.",
    cargando: "Buscando os clubes…",
    vacio: "Você ainda não está em nenhum clube com a conta {{correo}}. Quando liberarem seu acesso, toque em Verificar de novo.",
    vacioDueno: "Os clubes são criados e consultados em Clubes do app. Para trabalhar dentro de um, esse clube precisa liberar você.",
    error: "Não foi possível ler os clubes.",
    cambiar: "Trocar de clube",
    elegido: "Clube",
    hasta: "Até {{fecha}} · somente leitura",
    soloLecturaTitulo: "Você saiu deste clube em {{fecha}}.",
    soloLecturaTexto: "Você vê o que foi registrado até esse dia. Não dá para adicionar nem alterar nada.",
    soloLecturaCambio: "Somente leitura: você saiu deste clube.",
    salirDe: "Sair de {{club}}",
  },
  partido: {
    reanudarTitulo: "Retomar o {{periodo}}?",
    reanudarTexto: "O final registrado ({{final}}) é apagado e o relógio volta a correr. Se depois você tocar em Finalizar, fica a hora desse momento.",
    reanudarSi: "Sim, retomar",
    seguirEditando: "Continuar editando",
    salirSinGuardarTitulo: "Sair sem salvar as alterações?",
    salirSinGuardarTexto: "O que você mudou neste registro ainda não foi salvo. Se sair, perde.",
    salirSinGuardarSi: "Sim, sair",
    descartarFormacionTitulo: "Descartar a escalação não salva?",
    descartarFormacionTexto: "Você mudou a escalação e ainda não salvou. Se descartar, fica a que a partida tem.",
    descartarFormacionSi: "Descartar",
    sinClubesConPartido: "Você não tem nenhum clube com Jogo habilitado. Peça a quem administra o seu clube para adicionar você.",
    celularLleno: "Não foi possível salvar no celular: não há espaço. Não limpe a partida e salve-a de novo quando houver sinal.",
    celularLlenoCambios: "Não foi possível salvar as alterações no celular: não há espaço. Libere espaço e salve-as de novo.",
    borradorSinLugar: "Não há espaço no celular para salvar a partida em andamento. Salve-a ou libere espaço antes de fechar o app: senão, o que foi registrado se perde.",
    equipoSinPermisoRenombrar: "Você não tem permissão para mudar o nome desta equipe. Quem muda é quem administra o clube.",
    equipoRepetido: "Já existe uma equipe com esse nome.",
    equipoSinNombre: "Escreva o nome da equipe.",
    equipoErrorRenombrar: "Não foi possível mudar o nome. Verifique o sinal e tente de novo.",
    equipoNombreCambiado: "Nome alterado",
    equipoAhoraEn: "Agora você está em {{club}}",
    equipoPistaCambiar: "Cada equipe vê só as suas partidas e o seu elenco. Aqui aparecem os clubes dos quais você faz parte.",
    equipoPistaElegir: "Se o seu clube já está na lista, toque nele: você vai ver todas as partidas e o elenco, sem registrar nada de novo.",
    equipoTitulo: "Equipe",
    equipoSubtitulo: "Ajustes · Equipe",
    equipoElegirTitulo: "De qual equipe você é?",
    equipoElegirTexto: "O app salva as partidas e o elenco de cada clube separadamente. Escolha o seu para começar.",
    equipoTuyo: "Sua equipe",
    equipoNombreVacio: "Sem nome",
    equipoNombre: "Nome da equipe",
    equipoPistaEscudo: "O escudo não é enviado: ele é buscado pelo nome e fica salvo no telefone. Corrigir o nome não faz você perder as partidas registradas.",
    equipoGuardarNombre: "Salvar nome",
    equipoCambiar: "Trocar de equipe",
    equipoElegir: "Escolha sua equipe",
    volverAjustes: "Voltar aos Ajustes",
  },
  openfield: {
    abriendoTitulo: "Um momento…",
    abriendoTexto: "Estamos conectando com o OpenField.",
    sinAccesoTitulo: "Sem acesso à Rotina diária",
    errorTitulo: "Não conseguimos conectar com o OpenField",
    errorTexto: "Não foi possível abrir a sessão do OpenField. Tente de novo.",
    iniciaSesion: "Entre na sua conta para acessar o OpenField.",
    servidorCaido: "O OpenField não responde: você pode continuar trabalhando e tentar de novo daqui a pouco.",
    reintentando: "Tentando…",
    sinCatapult: "Seu clube ainda não conectou o Catapult no app.",
  },
  cuentas: {
    kicker: "Administração",
    titulo: "Contas",
    texto: "Quem entra no seu clube e quais módulos cada um usa. As mudanças valem na hora.",
    club: "Clube",
    clubTexto: "Quem sai continua vendo o que foi registrado até o último dia, sem poder alterar nada. Se voltar, é reincorporado com a mesma conta.",
    sinClubes: "Você não administra nenhum clube.",
    invitarTitulo: "Convidar alguém",
    invitarTexto: "Escreva o e-mail com o qual a pessoa vai se cadastrar. Entra como staff; se já tiver conta, entra na hora.",
    correo: "E-mail",
    invitar: "Convidar",
    invitando: "Convidando…",
    invitado: "Convite pronto. Avise {{correo}} para se cadastrar com esse e-mail.",
    entroYa: "{{correo}} já tinha conta: entrou no clube.",
    yaEsta: "Essa conta já está no clube.",
    invitacionesTitulo: "Convites abertos",
    vacioInvitaciones: "Não há convites aguardando.",
    venceEl: "Vence em {{fecha}}",
    invitacionesVencidasTitulo: "Convites vencidos",
    vencida: "Vencido",
    vencioEl: "Venceu em {{fecha}}: para que entre, convide de novo",
    copiarMensaje: "Copiar mensagem",
    copiado: "Mensagem copiada. Cole no WhatsApp ou num e-mail.",
    mensajeInvitacion: "Convidei você para {{club}} no Registro Partido. Entre em {{enlace}} e crie sua conta com este e-mail: {{correo}}.",
    cancelarInvitacion: "Cancelar",
    invitacionCancelada: "Convite cancelado.",
    miembrosTitulo: "No clube",
    exMiembrosTitulo: "Saíram",
    vacioMiembros: "Ainda não há ninguém no clube.",
    vacioExMiembros: "Ninguém saiu do clube.",
    desdeEl: "No clube desde {{fecha}}",
    hastaEl: "Até {{fecha}} · somente leitura",
    roles: {
      admin: "Administrador do clube",
      staff: "Staff",
    },
    modulos: {
      partido: "Jogo",
      flujo: "Rotina diária",
      lesiones: "Lesões",
      evaluaciones: "Avaliações",
    },
    ningunModulo: "nenhum módulo",
    darBaja: "Dar baixa",
    reincorporar: "Reincorporar",
    reincorporado: "{{correo}} voltou ao clube.",
    dadoDeBaja: "{{correo}} saiu do clube. Vê o que foi registrado até o último dia.",
    verHistoria: "Histórico",
    historiaTitulo: "{{correo}} em {{club}}",
    sinHistoria: "Ainda não há movimentos.",
    porQuien: "por {{correo}}",
    movimientos: {
      alta: "Entrou no clube ({{rol}}; {{modulos}})",
      baja: "Saiu do clube: último dia {{fecha}}",
      reincorporacion: "Voltou ao clube",
      rol: "Passou a {{rol}}",
      modulos: "Módulos: {{modulos}}",
      borrado: "A vinculação foi apagada",
    },
    bajaTitulo: "Qual foi o último dia no clube?",
    bajaTexto: "{{correo}} vai continuar vendo o que foi registrado em {{club}} até esse dia, sem poder alterar nada.",
    bajaFecha: "Último dia no clube",
    siBaja: "Sim, dar baixa",
    cuentaBloqueada: "Conta bloqueada",
    cuentaPendiente: "Conta pendente",
    tuCuenta: "Sua conta",
    dueno: "Dono do app",
    quePuedeUsar: "O que {{correo}} pode usar",
    laCuenta: "A conta",
    sinCorreo: "(sem e-mail)",
    errorLeer: "Não foi possível ler as contas.",
    errorClubes: "Não foi possível ler as pessoas do clube.",
    errorClub: "Não foi possível alterar a vinculação.",
    errorUltimoAdmin: "É o último administrador do clube: nomeie outro antes.",
    errorDuenoProtegido: "Essa conta não pode ser removida nem alterada pelo clube: só ela pode sair.",
    errorHastaFutura: "O último dia não pode ser uma data futura.",
    errorCorreo: "Escreva um e-mail válido.",
    errorInvitacionRepetida: "Já há um convite aberto para esse e-mail.",
    errorSinPermiso: "Você não tem permissão para fazer isso.",
    errorFaltaMigracion: "Falta atualizar a base (contas v2): é preciso rodar a migração.",
    errorHistorial: "Não foi possível ler o histórico.",
    errorInvitaciones: "Não foi possível ler os convites.",
    errorInvitar: "Não foi possível salvar o convite.",
  },
  // Clubes do app: o painel dos donos da plataforma.
  panel: {
    kicker: "Plataforma",
    titulo: "Clubes do app",
    texto: "De cada clube você vê o nome, o e-mail da entidade, o do administrador e quantas pessoas tem. Nada das pessoas nem dos dados.",
    crearTitulo: "Criar um clube",
    nombre: "Nome do clube",
    correoEntidad: "E-mail da entidade (opcional)",
    zona: "Fuso horário",
    crear: "Criar clube",
    creando: "Criando…",
    creado: "{{club}} foi criado. Você não fica dentro: entra quem o clube liberar.",
    crearAyuda: "O clube começa vazio. O fuso horário depois só muda por SQL.",
    clubesTitulo: "Clubes",
    vacioClubes: "Ainda não há clubes.",
    entidad: "Entidade: {{correo}}",
    sinEntidad: "Sem entidade",
    administrador: "Administrador: {{correo}}",
    sinAdministrador: "Sem administrador",
    personas_one: "{{n}} pessoa",
    personas_other: "{{n}} pessoas",
    asignar: "Definir entidade",
    cambiar: "Trocar",
    sacar: "Remover",
    entidadTitulo: "Entidade de {{club}}",
    entidadTexto: "O e-mail da conta que representa o clube. Por enquanto é só um dado.",
    entidadCorreo: "E-mail da entidade",
    guardar: "Salvar",
    cambiarTitulo: "Trocar a entidade de {{club}}?",
    cambiarTexto: "Antes: {{anterior}}. Agora: {{nuevo}}. Fica registrado em Movimentos e no histórico do clube.",
    siCambiar: "Sim, trocar",
    sacarTitulo: "Remover a entidade de {{club}}?",
    sacarTexto: "{{correo}} deixa de aparecer como entidade do clube.",
    siSacar: "Sim, remover",
    entidadGuardada: "Pronto: a entidade de {{club}} é {{correo}}.",
    entidadSacada: "{{club}} ficou sem entidade.",
    pedidosTitulo: "Pedidos de clubes que não estão no app",
    pedidosTexto: "Pessoas que pediram para entrar num clube que não está no app. Envie para o clube certo (lá decide o administrador) ou recuse.",
    vacioPedidos: "Não há pedidos sem clube.",
    clubEscrito: "Escreveu: {{club}}",
    pais: "País: {{pais}}",
    pedidoDel: "Pediu em {{fecha}}",
    mandarAClub: "Enviar a um clube",
    elegirClub: "Para qual clube enviar?",
    derivado: "O pedido de {{correo}} foi para {{club}}: agora decide o administrador.",
    rechazar: "Recusar",
    rechazarTitulo: "Recusar o pedido?",
    rechazarTexto: "{{correo}} não vai entrar por este pedido. Pode pedir de novo.",
    siRechazar: "Sim, recusar",
    rechazado: "Pedido recusado.",
    duenosTitulo: "Donos do app",
    principal: "Dono principal",
    tuCuenta: "Sua conta",
    soloPrincipal: "Só o dono principal inclui ou remove donos.",
    sumarTitulo: "Incluir subdono",
    sumarTexto: "Precisa ter conta no app com o e-mail confirmado. Pode fazer tudo o que você faz, menos incluir, remover ou passar donos.",
    correo: "E-mail",
    sumar: "Incluir",
    sumando: "Incluindo…",
    sumado: "{{correo}} agora é subdono.",
    quitar: "Remover",
    quitarTitulo: "Remover {{correo}} dos donos?",
    quitarTexto: "Deixa de ver este painel. Os clubes dessa conta não mudam.",
    siQuitar: "Sim, remover",
    quitado: "{{correo}} não é mais dono.",
    traspasar: "Passar o papel de dono principal",
    traspasarTitulo: "Passar o papel de dono principal para {{correo}}?",
    traspasarTexto: "Você fica como subdono e só essa conta vai poder incluir, remover ou passar donos. Para confirmar, escreva o e-mail dela.",
    traspasarConfirmar: "Escreva {{correo}}",
    siTraspasar: "Sim, passar o papel",
    traspasado: "{{correo}} é o dono principal. Você ficou como subdono.",
    movimientosTitulo: "Movimentos",
    vacioMovimientos: "Ainda não há movimentos.",
    porQuien: "por {{correo}}",
    automatico: "automático",
    movimientos: {
      semilla: "A plataforma começou",
      crearClub: "Clube criado",
      entidad: "Entidade",
      sumarSubdueno: "Incluiu um subdono",
      quitarSubdueno: "Removeu um subdono",
      traspaso: "Passou o papel de dono principal",
      derivarPedido: "Enviou um pedido a um clube",
      rechazarPedido: "Recusou um pedido sem clube",
    },
    error: {
      generico: "Não foi possível fazer. Tente de novo.",
      faltaMigracion: "Falta atualizar a base (donos e pedidos). É preciso rodar a migração antes de usar este painel.",
      sinPermiso: "Você não tem permissão para fazer isso.",
      soloDuenos: "Este painel é só para os donos do app.",
      soloDuenoPrincipal: "Isso só o dono principal faz.",
      duenoPrincipalInvalido: "Essa conta não pode ser dona principal: precisa estar liberada e com o e-mail confirmado.",
      duenoPrincipal: "O dono principal não pode ser removido.",
      nombreInvalido: "Escreva o nome do clube (até 60 letras).",
      nombreRepetido: "Já existe um clube com esse nome.",
      zonaHorariaInvalida: "Esse fuso horário não existe.",
      clubInexistente: "Esse clube não existe mais.",
      correoInvalido: "Escreva um e-mail válido.",
      entidadEsDueno: "Um dono do app não pode ser a entidade de um clube.",
      entidadRepetida: "Esse e-mail já é a entidade de outro clube.",
      cuentaInexistente: "Não há nenhuma conta com esse e-mail.",
      correoSinConfirmar: "Essa conta ainda não confirmou o e-mail.",
      cuentaBloqueada: "Essa conta está bloqueada.",
      yaEsDueno: "Essa conta já é dona do app.",
      esEntidad: "Essa conta é a entidade de um clube: não pode ser dona.",
      noEsSubdueno: "Essa conta não é subdona.",
      pedidoCerrado: "Esse pedido não está mais aberto.",
      clubSinAdmin: "Esse clube ainda não tem administrador: o pedido não pode ser enviado para lá.",
    },
  },
  // Pedidos de acesso: quem não tem convite pede para entrar num clube e espera.
  pedidos: {
    titulo: "Em qual clube você quer entrar?",
    texto: "Escreva o nome do clube e envie o pedido. Quando liberarem, você entra com esta conta.",
    club: "Clube",
    clubEjemplo: "Nome do clube",
    pais: "País",
    paisEjemplo: "Opcional",
    mandar: "Enviar pedido",
    mandando: "Enviando…",
    esperandoTitulo: "Aguardando autorização de {{club}}",
    esperandoTexto: "Seu pedido já foi enviado. Quando liberarem, toque em Verificar de novo.",
    cancelar: "Cancelar pedido",
    cancelando: "Cancelando…",
    rechazado: "Seu pedido para {{club}} não foi aceito. Você pode pedir de novo.",
    delClubTitulo: "Pedidos de acesso",
    vacioDelClub: "Ninguém pediu para entrar.",
    pidioEl: "Pediu em {{fecha}}",
    aceptar: "Aceitar",
    aceptarTitulo: "O que {{correo}} pode usar?",
    aceptarTexto: "Entra em {{club}} como staff com os módulos que você marcar. Depois mudam como sempre.",
    siAceptar: "Sim, aceitar",
    aceptado: "{{correo}} já está no clube.",
    rechazar: "Recusar",
    rechazarTitulo: "Recusar o pedido?",
    rechazarTexto: "{{correo}} não entra em {{club}}. Sai desta lista e pode pedir de novo.",
    siRechazar: "Sim, recusar",
    rechazadoAviso: "Pedido recusado.",
    salirTitulo: "Sair de {{club}}?",
    salirTexto: "Hoje é seu último dia: você vai continuar vendo o que foi registrado até hoje, sem alterar nada. Para voltar, precisam liberar você de novo.",
    siSalir: "Sim, sair",
    saliste: "Você saiu de {{club}}.",
    error: {
      generico: "Não foi possível fazer. Tente de novo.",
      faltaMigracion: "Falta atualizar a base (pedidos de acesso).",
      sinPermiso: "Você não tem permissão para fazer isso.",
      clubInvalido: "Escreva o nome do clube (entre 2 e 80 letras).",
      yaHayUnPedido: "Você já tem um pedido aguardando.",
      soloAdmin: "Isso quem decide é o administrador do clube.",
      pedidoCerrado: "Esse pedido já foi decidido ou cancelado.",
      cuentaBloqueada: "Essa conta está bloqueada.",
      correoSinConfirmar: "Primeiro confirme seu e-mail (chegou uma mensagem) e entre de novo.",
      ultimoAdmin: "Você é o único administrador do clube: por enquanto não pode sair.",
      duenoProtegido: "Essa conta não pode ser removida nem alterada pelo clube: só ela pode sair.",
      noEsMiembro: "Você não está mais nesse clube.",
    },
  },
  lesiones: {
    titulo: "Lesões",
    hoy: "Lesionados hoje",
    activas_one: "{{n}} lesão ativa",
    activas_other: "{{n}} lesões ativas",
    sinActivas: "Não há lesões ativas. Todo o elenco está disponível.",
    nueva: "Nova lesão",
    pasos: {
      dados_geraisTexto: "Quem se lesionou? Busque o jogador pelo nome.",
      descricao_geralTexto: "Que tipo de lesão foi e onde: na figura, primeiro a zona e depois a parte. A imagem, se já houver.",
      descricao_especificaTexto: "Ligamento ou músculo, se já se sabe. Dá para completar depois.",
      descricao_contextualTexto: "Como, quando e onde aconteceu.",
      evolucaoTexto: "A data de início, e as de transição, retorno e alta quando houver.",
      observacoesTexto: "O que for preciso anotar.",
      paso: "Passo {{n}} de {{total}}",
      siguiente: "Avançar",
      atras: "Voltar",
      guardar: "Salvar a lesão",
      buscar: "Buscar jogador...",
      ningunJugador: "Nenhum jogador com esse nome.",
      cambiar: "Trocar",
      sinJugador: "Escolha o jogador para continuar.",
      opcional: "Opcional",
    },
    darAlta: "Alta médica",
    borrar: "Excluir lesão",
    borrarTitulo: "Excluir esta lesão?",
    borrarTexto: "A lesão de {{jugador}} será excluída. Fica anotado no histórico de alterações.",
    siBorrar: "Sim, excluir",
    salirTitulo: "Sair sem salvar?",
    salirTexto: "O que você preencheu nesta lesão será perdido.",
    siSalir: "Sim, sair",
    seguirCargando: "Continuar preenchendo",
    borrada: "Lesão excluída",
    editar: "Editar",
    verDetalle: "Ver detalhes",
    caso: "Caso {{n}}",
    dias_one: "{{n}} dia",
    dias_other: "{{n}} dias",
    horas_one: "{{n}} hora",
    horas_other: "{{n}} horas",
    anios_one: "{{n}} ano",
    anios_other: "{{n}} anos",
    desde: "desde {{fecha}}",
    altaEl: "alta em {{fecha}}",
    etapa: {
      lesionado: "Lesionado",
      transicion: "Em transição",
      entrenando: "Treinando",
      alta: "Com alta",
      sinFecha: "Sem data de início",
    },
    fueraDeDatos: "Não está em Dados básicos",
    sinFecha: {
      titulo_one: "{{n}} lesão sem data de início",
      titulo_other: "{{n}} lesões sem data de início",
      texto: "Vieram assim do Excel. Não contam como ativas, nem em dias perdidos, nem nos relatórios até completar a data: abra cada uma e edite.",
    },
    altaTitulo: "Dar a alta médica?",
    altaTexto: "{{jugador}} volta a competir a partir da data que você escolher.",
    altaFecha: "Retorno à competição",
    siAlta: "Sim, dar alta",
    formNueva: "Nova lesão",
    formEditar: "Editar lesão",
    sinJugadores: "Não há jogadores cadastrados. Eles são adicionados em Dados básicos.",
    guardado: "Lesão salva",
    altaGuardada: "Alta salva",
    avisoRecidiva: "Atenção: já teve uma lesão em {{parte}} ({{lado}}) em {{fecha}}. Pode contar como recorrência ou recidiva.",
    graficos: {
      opcion: "Relatórios gráficos",
      opcionTexto: "Os gráficos do elenco: lesões e dias perdidos c/1000 h dos períodos salvos, partes do corpo, lesões por jogador e treinamento e partidas",
      titulo: "RELATÓRIOS GRÁFICOS DE LESÕES",
      alDia: "Em {{fecha}}",
      ir: "Ir para",
      filtros: "Filtros",
      secciones: {
        lesiones: "N° de lesões c/1000 h",
        dias: "N° de dias perdidos c/1000 h",
        partes: "Partes do corpo",
        jugador: "Lesões por jogador",
        momentos: "Treinamento e partidas",
      },
      anio: "Ano",
      todosLosAnios: "Todos os anos",
      anioNota: {
        hasta: "O ano de cada período é o da sua data final.",
        desde: "O ano de cada período é o da sua data de início.",
      },
      sinPeriodos: "Ainda não há períodos salvos. Eles são salvos em «Lesões c/1000h e dias perdidos».",
      sinPeriodosDelAnio: "Não há períodos salvos de {{anio}}.",
      irAPeriodos: "Salvar períodos",
      todos: "Todos",
      filtro: "{{campo}}: {{valor}}",
      sinDato: "Sem dado",
      sinLesiones: "Não há lesões com estes filtros.",
      cuentanTodas: "Contam todas as lesões com data de início e «{{campo}}» preenchido, de qualquer data.",
      elegidos_one: "{{n}} selecionado",
      elegidos_other: "{{n}} selecionados",
      cuentanConSerie: "Contam as lesões com data de início, «{{contado}}» e «{{campo}}» preenchidos, de qualquer data.",
      cuentanMomentos: "Contam as lesões com data de início, «{{contado}}» e «{{campo}}» preenchidos, pelo ano da data de início.",
    },
    cadaMil: {
      opcion: "Lesões c/1000h e dias perdidos",
      opcionTexto: "Escolha as datas: lesões e dias perdidos do período, os minutos de treino e a cada 1000 horas. Salve com um nome para comparar",
      titulo: "LESÕES C/1000 H E DIAS PERDIDOS",
      elegir: "Escolha a data de início, a final e um nome para o período",
      baseCompleta: "Base completa",
      inicio: "Início",
      final: "Final",
      sinInicio: "Sem início: desde a primeira lesão.",
      nombre: "Nome do período",
      nombreEjemplo: "Ex.: Primeiro semestre",
      minutos: "Minutos de treino",
      horas: "Horas de treino",
      resultado: "Lesões e dias perdidos do período",
      nLesiones: "N° de lesões",
      nDias: "N° de dias perdidos",
      faltaGps: "Faltam os minutos do GPS: as contas a cada 1000 horas aparecem quando a base do GPS estiver no app.",
      guardar: "Salvar o período",
      yaGuardado: "Período salvo",
      guardado: "Período salvo",
      faltaNombre: "Falta o nome do período selecionado.",
      faltaFinal: "Escolha a data final.",
      guardados: "Períodos salvos",
      sinGuardados: "Ainda não há períodos salvos. Escolha as datas, dê um nome e salve para comparar depois.",
      borrar: "Excluir o período {{nombre}}",
      borrarTitulo: "Excluir o período?",
      borrarTexto: "«{{nombre}}» sai da lista de períodos salvos. As lesões não são alteradas.",
      borrado: "Período excluído",
    },
    periodos: {
      error: {
        noLeer: "Não foi possível ler os períodos salvos.",
        noGuardar: "Não foi possível salvar o período.",
        noBorrar: "Não foi possível excluir o período.",
        repetido: "Já há um período com esse nome.",
        fechas: "A data de início não pode ser depois da final.",
        nombre: "Escreva um nome de até 80 letras.",
        faltaMigracion: "Para salvar períodos falta rodar no Supabase o SQL dos períodos (20261009_lesiones_periodos.sql).",
      },
    },
    importar: {
      boton: "Colar do Excel",
      titulo: "Colar lesões do Excel",
      texto: "No Excel, na aba Antecedentes BD, copie a tabela desde a linha de cabeçalhos (a que diz N° de Caso, Nome e Sobrenome…) até a última lesão, e cole aqui. Antes de carregar dá para ver o que acontece com cada linha. Entram todas: as que não têm data de início ficam para completar.",
      pegarAca: "Cole aqui o que você copiou do Excel",
      borrar: "Apagar o colado",
      sinCabeceras: "Não encontrei a linha de cabeçalhos. Copie a tabela junto com a linha que diz Nome e Sobrenome.",
      sinFilas: "Abaixo dos cabeçalhos não há lesões.",
      filas_one: "{{n}} linha no colado",
      filas_other: "{{n}} linhas no colado",
      nuevas_one: "{{n}} para carregar",
      nuevas_other: "{{n}} para carregar",
      yaEstan_one: "{{n}} já está no app",
      yaEstan_other: "{{n}} já estão no app",
      sinFechas_one: "{{n}} sem data de início",
      sinFechas_other: "{{n}} sem data de início",
      conProblemas_one: "{{n}} com problemas",
      conProblemas_other: "{{n}} com problemas",
      porElegir_one: "{{n}} para escolher",
      porElegir_other: "{{n}} para escolher",
      noVan_one: "{{n}} não é carregada",
      noVan_other: "{{n}} não são carregadas",
      fueraDeDatos_one: "{{n}} nome não está em Dados básicos: toque nele para escolher o que fazer, ou salve assim mesmo.",
      fueraDeDatos_other: "{{n}} nomes não estão em Dados básicos: toque em cada um para escolher o que fazer, ou salve assim mesmo.",
      guardarTodasIgual_one: "Salvar assim mesmo a que não está em Dados básicos",
      guardarTodasIgual_other: "Salvar assim mesmo as {{n}} que não estão em Dados básicos",
      quienEs: "O que fazemos com {{nombre}}?",
      comoPersona: "Salvar com este nome (não é adicionado a Dados básicos)",
      noCargar: "Não carregar",
      es: "É {{jugador}}",
      seGuardaComoPersona: "Não está em Dados básicos: a lesão é salva com este nome e o nome não é adicionado a Dados básicos.",
      seGuardaComo: "Não está em Dados básicos: a lesão é salva como {{nombre}}, escrito como em outra lesão da mesma pessoa, e o nome não é adicionado a Dados básicos.",
      faltaCompletar: "É carregada sem {{columnas}}: fica para completar.",
      caso: "Caso {{n}}",
      sinCaso: "Sem N° de caso",
      estado: {
        nueva: "Será carregada",
        yaEsta: "Já está no app",
        sinJugador: "Não está em Dados básicos",
        dudoso: "Quem é?",
        comoPersona: "Salva com este nome",
        noVa: "Não é carregada",
        conProblemas: "Não é carregada",
      },
      sinJugador: "Este nome não está em Dados básicos. Escolha se é salva com este nome (não é adicionado a Dados básicos), se é um jogador da lista ou se não é carregada.",
      jugadorDudoso: "Em Dados básicos há mais de um jogador com um nome assim: escolha qual é, ou salve com este nome.",
      casoOcupado: "Já há outra lesão com este N° de caso no app.",
      casoRepetido: "Este N° de caso aparece duas vezes no colado.",
      nombreLargo: "O nome é longo demais para salvar (até 120 letras).",
      sinNombre: "Falta o nome: não se sabe de quem é.",
      sinNombreFila: "Sem nome",
      plantelSinLeer: "Não foi possível ler Dados básicos, e sem isso não se sabe quem é cada um. Volte e tente de novo.",
      quedanSinElegir_one: "{{n}} nome continua sem escolher: essa lesão não é carregada até você escolher o que fazer.",
      quedanSinElegir_other: "{{n}} nomes continuam sem escolher: essas lesões não são carregadas até você escolher o que fazer.",
      aviso: "«{{valor}}» não foi entendido em {{columna}}: fica vazio.",
      cargar_one: "Carregar {{n}} lesão",
      cargar_other: "Carregar {{n}} lesões",
      nadaQueCargar: "Nada para carregar",
      cargando: "Carregando {{n}} de {{total}}…",
      listo_one: "Pronto: {{n}} lesão carregada.",
      listo_other: "Pronto: {{n}} lesões carregadas.",
      fallaron_one: "{{n}} lesão não pôde ser carregada:",
      fallaron_other: "{{n}} lesões não puderam ser carregadas:",
      fallo: "{{caso}} · {{nombre}}: {{error}}",
    },
    error: {
      jugador: "Escolha um jogador.",
      fecha: "Informe a data de início da lesão.",
      fechaFutura: "A data de início não pode ser no futuro.",
      fechaAntes: "As datas de transição, retorno e alta não podem ser anteriores ao início.",
      fechaFuturaOtra: "Nenhuma data pode ser no futuro.",
      parte: "Escolha a parte do corpo lesionada.",
      lado: "Escolha o lado.",
      tipo: "Escolha o tipo de lesão.",
      imagen: "A hora da imagem não é válida.",
      imagenAntes: "A imagem não pode ser de antes do dia da lesão.",
      lesionDespuesDeImagen: "A lesão não pode começar depois da imagem ({{imagen}}).",
      solapada: "Já existe uma lesão ativa em {{parte}} ({{lado}}) para este jogador.",
      repetida: "Essa lesão já está cadastrada: este jogador já tem uma em {{parte}} ({{lado}}) que começa no mesmo dia.",
      noGuardar: "Não foi possível salvar a lesão.",
      noBorrar: "Não foi possível excluir a lesão.",
      noLeer: "Não foi possível ler as lesões.",
      faltaMigracion: "O banco ainda não tem as tabelas de lesões: falta executar a migração 20261002_lesiones_excel.sql no Supabase.",
      faltaMigracionPersonas: "Para salvar lesões sem data de início ou de alguém que não está em Dados básicos falta rodar no Supabase o SQL 20261010_lesiones_sin_fecha_y_personas.sql.",
      sinPermiso: "Sua conta não tem permissão para registrar lesões.",
    },
    reportes: {
      titulo: "Relatórios",
      texto: "O que as lesões cadastradas mostram, de um jogador ou do elenco.",
      ver: "Ver relatórios",
      individual: "Relatório individual",
      individualTexto: "Um jogador: lesões e dias perdidos a cada 1000 horas contra a referência do elenco, seu mapa corporal e seu histórico",
      grupal: "Relatório do elenco",
      grupalTexto: "O elenco: a cada 1000 horas, meses, regiões, tipos e quem perdeu mais dias",
      crear: "Criar relatórios",
      crearTexto: "O próximo passo: montar seus próprios relatórios com blocos (um gráfico, uma tabela ou um número), escolhendo o que medir, como separar e com quais filtros, e salvá-los para o clube.",
      individualTitulo: "Relatório individual de lesões",
      grupalTitulo: "RELATÓRIO DE LESÕES DO ELENCO",
      volver: "Relatórios",
      imprimir: "Imprimir ou salvar em PDF",
      elegirJugador: "De qual jogador?",
      cambiarJugador: "Trocar jogador",
      periodo: "Período",
      periodos: {
        anio: "Este ano",
        doce: "Últimos 12 meses",
        todo: "Tudo",
        medida: "Escolher datas",
      },
      desde: "De",
      hasta: "Até",
      cuales: "Quais lesões",
      sinLeves: "Sem leves",
      soloMusculares: "Só LM",
      todas: "Todas as lesões",
      nacimiento: "Nascimento",
      pie: "Pé dominante",
      kpiLesiones: "Lesões",
      kpiDias: "Dias perdidos",
      kpiActivas: "Abertas hoje",
      kpiJugadores: "Jogadores lesionados",
      kpiPromedio: "Dias por lesão (com alta)",
      kpiRecurrentes: "Recorrentes",
      cadaMil: "A cada 1000 horas",
      lesionesMil: "Lesões c/ 1000 h",
      diasMil: "Dias perdidos c/ 1000 h",
      tiposTodos: "Tipos (TUDO)",
      tiposLM: "Tipos (Só LM)",
      severidadTodas: "Severidade (TUDO)",
      severidadSinLeves: "Severidade (SEM LEVES)",
      indicadores: "Indicadores de lesão",
      tasas: "Taxas por 1000 horas",
      variante: "{{severidad}} e {{tipos}}",
      referencia: "Referência",
      comparado: {
        peor: "Superior à referência",
        mejor: "Inferior à referência",
        igual: "Igual à referência",
      },
      superiorRef: "Superior à referência",
      inferiorRef: "Inferior à referência",
      queEsRef: "Referência = o valor do elenco (VR)",
      porcentajeVsRef: "{{valor}} vs referência",
      lesionesPorMil: "Lesões",
      diasPorMil: "Dias perdidos",
      porMil: "/ 1000 h",
      unidadLesiones: "lesões / 1000 h",
      unidadDias: "dias / 1000 h",
      mapaCorporal: "Mapa corporal de lesões",
      vistas: {
        frente: "Anterior",
        espalda: "Posterior",
      },
      mapaNota: "Quanto maior e mais intensa a mancha, mais lesões nesse lugar. Direita e esquerda são as do jogador.",
      historialLesiones: "Histórico de lesões",
      registros_one: "{{n}} registro",
      registros_other: "{{n}} registros",
      cuentan: "Contam as lesões com {{criterio}}.",
      cuentanLm: "Em «{{lm}}», dessas, as do tipo {{tipos}}.",
      faltaGps: "Faltam os minutos do GPS: sem eles não dá para calcular as contas a cada 1000 horas.",
      sinLesionesJugador: "Não tem lesões cadastradas.",
      sinLesiones: "Não há lesões neste período com estes filtros.",
      dondeSeLesionan: "Onde se lesionam",
      abierta: "Sem alta",
      porMes: "Lesões por mês",
      masDias: "Quem perdeu mais dias",
    },
    historial: {
      titulo: "Histórico individual",
      texto: "Escolha um jogador e veja todas as lesões dele, como na base.",
      buscar: "Buscar um jogador...",
      sinLesiones: "Este jogador não tem lesões registradas.",
      cantidad_one: "{{n}} lesão",
      cantidad_other: "{{n}} lesões",
    },
    cuerpo: {
      figura: "Figura do corpo",
      donde: "Onde foi a lesão",
      cuerpo: "Corpo",
      vista: "Como ver a figura",
      frente: "De frente",
      espalda: "De costas",
      derecha: "DIREITA",
      izquierda: "ESQUERDA",
      tocaZona: "Toque na zona da lesão.",
      regiones: {
        cabeza: "Cabeça e pescoço",
        tronco: "Tronco",
        brazo_derecho: "Braço direito",
        brazo_izquierdo: "Braço esquerdo",
        pierna_derecha: "Perna direita",
        pierna_izquierda: "Perna esquerda",
      },
      queLado: "De que lado?",
      elegido: "{{parte}} · {{lado}}",
      ubicacion: "Localização",
      estructuraTexto: "Toque no que corresponder: estão as opções das listas que vão nesta parte do corpo.",
      estructuraFigura: "Toque na figura o músculo, o tendão ou o ligamento, ou escolha abaixo. O que está escuro não está nas listas desta parte.",
      capa: "Quais músculos ver",
      capas: {
        superficie: "Superficiais",
        profunda: "Profundos",
      },
      esquemas: {
        rodilla: "Joelho por dentro",
        tobilloAfuera: "Tornozelo por fora",
        tobilloAdentro: "Tornozelo por dentro",
        planta: "Planta do pé",
      },
      rotulos: {
        lca: "LCA",
        lcp: "LCP",
        lle: "LLE",
        lli: "LLI",
        ml: "ML",
        mm: "MM",
        anterior: "Anterior",
        medio: "Médio",
        posterior: "Posterior",
        sindesmosis: "Sindesmose",
        deltoideo: "Deltoide",
        musculos: "Músculos",
        aductor: "Adutor",
        fascia: "Fáscia",
        insercion: "Inserção",
      },
      leyenda: {
        musculos: "Músculos",
        tendones: "Tendões",
        ligamentos: "Ligamentos",
      },
      sinEstructuras: "Nas listas não há músculos nem ligamentos para esta parte do corpo.",
      tercios: {
        proximal: "Proximal",
        medio: "Médio",
        distal: "Distal",
      },
      deLaLista: "Escolher da lista",
      conFigura: "Escolher com a figura",
    },
    ficha: {
      resumen: "Resumo da lesão",
      secciones: "O que ver",
      diasDeBaja: "Dias de afastamento",
      cambios: "Alterações",
      ultimos: "Últimas alterações",
      ultimosTexto: "As 5 mais recentes",
      sinCambios: "Sem alterações registradas.",
      cambio: "{{fecha}} · {{quien}}",
      creada: "Registro",
      editada: "Edição",
      columnas: "Mudou: {{columnas}}",
    },
    ajustes: {
      titulo: "Ajustes",
      texto: "O que o app usa em Lesões.",
      cabeceras: "Cabeçalhos",
      cabecerasTexto: "Como se chama cada coluna do Excel",
      cabecerasAyuda: "Toque em um grupo ou em uma coluna para mudar o nome em cada idioma. As colunas também podem ser escondidas do formulário.",
      listas: "Listas",
      listasTexto: "As opções de cada lista suspensa",
      listasAyuda: "Toque em uma lista para adicionar, renomear ou esconder opções. O que já foi registrado não se perde.",
      volver: "Voltar aos Ajustes",
      volverListas: "Voltar às Listas",
      editarCabecera: "Cabeçalho",
      editarGrupo: "Grupo",
      grupoDe_one: "Grupo de {{n}} coluna",
      grupoDe_other: "Grupo de {{n}} colunas",
      grupoAyuda: "É a linha acima dos cabeçalhos: organiza a base, o registro por passos e a ficha.",
      editarOpcion: "Opção",
      nuevaOpcion: "Adicionar uma opção",
      nombre: "Nome neste idioma",
      nombreAyuda: "Para mudá-lo em outro idioma, troque o idioma do app e volte aqui.",
      mostrar: "Aparece",
      oculto: "Oculta",
      guardado: "Salvo",
      errorGuardar: "Não foi possível salvar a alteração.",
      opciones_one: "{{n}} opção",
      opciones_other: "{{n}} opções",
      porDefecto: "Do Excel: {{texto}}",
      faltaTexto: "Escreva o nome.",
      noSeOculta: "Esta coluna é necessária para registrar a lesão: aparece sempre.",
      seUbicanSolas: "As que você adicionar se posicionam sozinhas no corpo, pelo nome.",
      vaEn: "No corpo: {{partes}}",
      vaEnTodas: "Não se reconhece em que parte do corpo vai: aparece em todas",
      vaConTercio: "Terço: {{tercio}}",
      sinTercio: "Do músculo todo, sem terço",
    },
    estado: {
      cargando: "Lendo as lesões…",
      sinConexion: "Sem conexão. Lesões precisa de sinal para ler e salvar.",
    },
  },
};
