const jugadores = [
  "",
  "A MINDA",
  "A PRECIADO",
  "ALAN FRANCO",
  "ALEXSANDER",
  "ALONSO",
  "BERNARD",
  "CAUA SOARES",
  "CISSE",
  "CUELLO",
  "DUDU",
  "I ROMAN",
  "IGOR GOMES",
  "INDIO",
  "M ISEPPE",
  "KAUA PASCINI",
  "LYANCO",
  "M CASSIERRA",
  "MAYCON",
  "NATANAEL",
  "PATRICK",
  "REINIER",
  "RENAN LODI",
  "RUAN",
  "SCARPA",
  "T PEREZ",
  "V HUGO",
  "VICTOR",
  "VITAO",
  "LUIS GUSTAVO",
  "VENENO",
  "GUTTE",
  "THIAGO BORBAS",
  "KEVIN CASTANO"
];

export default jugadores;